import { defaultOutput } from "./createOutputDiagnosticsController";
import type { EngineSnapshot } from "./types";

export const createInitialEngineSnapshot = (): EngineSnapshot => ({
  fixtures: [],
  cues: [],
  cue_lists: [{ id: 1, label: "Bank 1", active_cue_id: null }],
  palettes: [],
  playback_executors: [{ id: 1, label: "Bank 1", cue_list_id: 1, page: 1, slot: 1, level: 1 }],
  playback_master: 1,
  active_cue_id: null,
  direct_child_timeline_transports: [],
  active_fade: null,
  programmer: { enabled: false, blind: false, values: [], dmx_previews: [] },
  timeline: {
    events: [],
    automations: [],
    video_automations: [],
    audio: null,
    audio_clips: [],
    audio_offset_ms: 0,
    audio_muted: false,
    playing: false,
    position_ms: 0,
    duration_ms: 0,
  },
  video: {
    layers: [],
    media_assets: [],
    compositions: [],
    outputs: [],
    mapping_presets: [],
    master_opacity: 1,
    blackout: false,
  },
  effects: [],
  node_graphs: [],
  output: defaultOutput,
  dmx_outputs: [defaultOutput],
  lighting_master: 1,
  submasters: [],
  blackout: false,
  authored_blackout: false,
  safety_blackout_engaged: false,
  clock: {
    bpm: 120,
    beat_phase: 0,
    beat_counter: 0,
    tap_count: 0,
    source: "Manual",
    external_sync_age_ms: null,
    external_sync_locked: false,
  },
  stage_map: { locked: false, min_x: -10, max_x: 10, min_z: -10, max_z: 10 },
  stage_map_presets: [],
  stage_objects: [],
  touch_surface: { pages: [] },
  dmx_preview: Array.from({ length: 512 }, () => 0),
  dmx_previews: [{ universe: 0, values: Array.from({ length: 512 }, () => 0) }],
  telemetry: {
    frame_counter: 0,
    enabled_effect_count: 0,
    supported_effect_count: 0,
    effects_over_supported_envelope: false,
    queue_depth: 0,
    queue_depth_abs_max: 0,
    queue_push_failure_count: 0,
    last_tick_interval_us: 0,
    tick_jitter_last_us: 0,
    tick_jitter_abs_max_us: 0,
    tick_jitter_stddev_us: 0,
    tick_jitter_p95_us: 0,
    tick_jitter_p99_us: 0,
    tick_jitter_samples: 0,
    last_command_queue_latency_us: 0,
    command_queue_latency_abs_max_us: 0,
    command_queue_latency_p95_us: 0,
    command_queue_latency_p99_us: 0,
    command_queue_latency_samples: 0,
    last_command_drain_count: 0,
    command_drain_abs_max: 0,
    command_drain_limit_hit_count: 0,
    last_command_to_dmx_tick_latency_us: 0,
    command_to_dmx_tick_latency_abs_max_us: 0,
    command_to_dmx_tick_latency_p95_us: 0,
    command_to_dmx_tick_latency_p99_us: 0,
    command_to_dmx_tick_latency_samples: 0,
    last_dmx_send_interval_us: 0,
    dmx_send_interval_min_us: 0,
    dmx_send_interval_max_us: 0,
    dmx_send_interval_samples: 0,
    low_latency_dmx_tick_request_count: 0,
    low_latency_dmx_tick_advance_count: 0,
    low_latency_dmx_tick_defer_count: 0,
    last_packet_bytes: 0,
    last_dmx_output_count: 0,
    last_dmx_send_success_count: 0,
    last_dmx_send_failure_count: 0,
    total_dmx_send_success_count: 0,
    total_dmx_send_failure_count: 0,
    last_dmx_route_results: [],
    last_error: null,
  },
});
