export type UiLocale = "en" | "ja";

export const uiLocaleStorageKey = "syndocal.uiLocale.v1";

const japaneseText: Record<string, string> = {
  "Project menu": "プロジェクトメニュー",
  "Unsaved project": "未保存プロジェクト",
  New: "新規",
  Save: "保存",
  "Save As": "名前を付けて保存",
  Load: "開く",
  "User Templates": "ユーザーテンプレート",
  "New from Template": "テンプレートから新規作成",
  "Outputs open disabled": "出力は無効で開きます",
  "Save as Template": "テンプレートとして保存",
  "Includes MIDI / OSC mappings": "MIDI / OSCマッピングを含む",
  Undo: "元に戻す",
  Redo: "やり直す",
  Recovery: "復旧",
  "Discard Recovery": "復旧データを破棄",
  Backups: "バックアップ",
  Delete: "削除",
  "Recent Projects": "最近使ったプロジェクト",
  "Clear Recent": "履歴を消去",
  "Load Sample": "サンプルを開く",
  "Run Smoke Test": "スモークテスト実行",
  "Export Diagnostics": "診断パッケージを出力",
  "Application Updates": "アプリ更新",
  "Check for Updates": "更新を確認",
  "Checking...": "確認中...",
  "Reading update configuration...": "更新設定を読込中...",
  "Signed update channel": "署名付き更新チャネル",
  "Signature verified": "署名を検証済み",
  "Verifying signature...": "署名を検証中...",
  "Signed artifact · project backup first": "署名付き成果物 · 先にプロジェクトをバックアップ",
  Interface: "表示",
  "Interface Scale": "表示倍率",
  "FULL SCREEN": "フルスクリーン",
  MAXIMIZED: "最大化",
  WINDOW: "ウィンドウ",
  "WINDOW MODE ERROR": "ウィンドウ表示エラー",
  "ESC EXIT": "ESC で終了",
  "F11 FULL SCREEN": "F11 フルスクリーン",
  "F11 RETRY": "F11 再試行",
  "Reset Layout": "レイアウトを初期化",
  Setup: "セットアップ",
  Control: "コントロール",
  Touch: "タッチ",
  Library: "ライブラリ",
  Profiles: "プロファイル",
  Patch: "パッチ",
  "Video I/O": "映像I/O",
  Mapping: "マッピング",
  Remote: "リモート",
  "Live Edit": "ライブ編集",
  Timeline: "タイムライン",
  "Linked Scene Blocks": "連動シーンブロック",
  "Scene Blocks": "シーンブロック",
  "SHOW SEQUENCE": "ショーシーケンス",
  "PLAY ONLY": "再生時のみ",
  "FULL CUE": "キュー全体",
  "Scene Block summary": "シーンブロック概要",
  Blocks: "ブロック",
  blocks: "ブロック",
  "Timeline visible range controls": "タイムライン表示範囲の操作",
  "Visible timeline range": "タイムライン表示範囲",
  "Pan Prev": "前の範囲へ",
  "Pan Next": "次の範囲へ",
  "Zoom Out": "縮小",
  "Zoom In": "拡大",
  "Zoom level": "ズームレベル",
  "Edit Projection in Video Setup": "映像セットアップで投影を編集",
  "Reveal Selected": "選択位置を表示",
  "Reveal Playhead": "再生位置を表示",
  "Clear overlap filter": "重複フィルターを解除",
  "Block #": "ブロック #",
  Points: "ポイント",
  LINKED: "連動",
  "Source Cue": "ソースキュー",
  "Source Cue edits update every placed instance.": "ソースキューの編集は配置済みの全インスタンスに反映されます。",
  "After jumps apply to Timeline Play only. External MTC/LTC timecode remains authoritative.":
    "後続ジャンプはタイムライン再生時のみ適用されます。外部MTC/LTCタイムコードが優先されます。",
  "Open the Timeline to inspect every linked placement.": "すべての連動配置を確認するにはタイムラインを開いてください。",
  "more · Open Timeline": "件追加 · タイムラインを開く",
  "Source / live status": "ソース／ライブ状態",
  "Instance timing and flow": "配置タイミングとフロー",
  "Lane is visual; the full linked Cue fires.": "レーンは表示上の区分です。連動キュー全体が発火します。",
  "Shared jump target picker": "共有ジャンプ先ピッカー",
  "Shared source Cue picker": "共有ソースキューピッカー",
  "Search source Cues": "ソースキューを検索",
  "Search number or name": "番号または名前を検索",
  "Search jump targets": "ジャンプ先を検索",
  "Search Scene Blocks": "シーンブロックを検索",
  "Find block ID, Cue, or name": "ブロックID、キュー、名前を検索",
  "Find ID, Cue, name, or start": "ID、キュー、名前、開始時刻を検索",
  "Find…": "検索…",
  "Source Cue result": "ソースキュー検索結果",
  "Apply Source": "ソースを適用",
  "Change…": "変更…",
  "Edit Source": "ソースを編集",
  "shown ·": "件表示 ·",
  total: "全件",
  "After target": "後続ターゲット",
  "Jump target placement": "ジャンプ先の配置",
  "Apply Target": "ターゲットを適用",
  "Choose target…": "ターゲットを選択…",
  "Scene Block pages": "シーンブロックのページ",
  Last: "最後",
  LIVE: "ライブ",
  PLAYHEAD: "再生位置",
  UNSAVED: "未保存",
  "OUTPUT:": "出力:",
  "ms ×": "ms × ループ",
  "ms left · After:": "ms 残り · 後続:",
  Actions: "操作",
  "Start ms": "開始 ms",
  "Duration ms": "長さ ms",
  Loops: "ループ回数",
  After: "後続",
  Continue: "続行",
  Jump: "ジャンプ",
  "Jump ·": "ジャンプ ·",
  "Repeat this block": "このブロックを繰り返す",
  "Add Linked Block": "連動ブロックを追加",
  "Block @ Playhead": "再生位置へブロック",
  "Save Block": "ブロックを保存",
  "Save Point": "ポイントを保存",
  "No Scene Blocks yet": "シーンブロックはまだありません",
  "Create a Cue before adding linked Scene Blocks.": "連動シーンブロックを追加する前にキューを作成してください。",
  "Select a source Cue, set its instance timing, then place the first linked block.":
    "ソースキューを選び、配置タイミングを設定して、最初の連動ブロックを配置してください。",
  "Place this Cue as a linked Scene Block at the current playhead.":
    "このキューを現在の再生位置へ連動シーンブロックとして配置します。",
  "Legacy instant trigger · set Duration to upgrade": "旧形式の即時トリガー · 長さを設定するとブロックへ変換",
  Mixer: "ミキサー",
  "VJ Desk": "VJデスク",
  "Import Media": "素材を読み込む",
  "Import video or still images to populate the clip grid.": "動画または静止画を読み込み、クリップグリッドへ追加します。",
  "Start your first VJ show": "最初のVJショーを始める",
  "Choose local video files to build the clip grid and stage the first clip.": "ローカル動画を選び、クリップグリッドを作成して先頭クリップをプレビュー待機にします。",
  "VJ Program is created Off and Blackout. No output window opens automatically.": "VJ ProgramはOff・Blackoutで作成されます。出力ウィンドウは自動で開きません。",
  "Choose media and set up the VJ show": "素材を選んでVJショーをセットアップ",
  "Setting Up…": "セットアップ中…",
  "Choose Media & Set Up": "素材を選んでセットアップ",
  "First-run VJ setup is only available for an empty video show.": "初回VJセットアップは空の映像ショーでのみ利用できます。",
  "VJ setup canceled. No project changes were made.": "VJセットアップをキャンセルしました。プロジェクトは変更されていません。",
  Cues: "キュー",
  "Edit Cues": "キューを編集",
  Done: "完了",
  Automation: "オートメーション",
  Playback: "プレイバック",
  Attributes: "属性",
  Effects: "エフェクト",
  "Lighting FX": "ライティングFX",
  "Show Timeline": "ショータイムライン",
  "FX Workspace": "FXワークスペース",
  "Effect Library": "エフェクトライブラリ",
  "Effect recipes": "エフェクトレシピ",
  "Effect Inspector": "エフェクトインスペクタ",
  Inspector: "インスペクタ",
  "New effect": "新規エフェクト",
  "Live Rack": "ライブラック",
  "Live FX Rack": "ライブFXラック",
  "FX rack surface": "FXラック表示",
  Stack: "スタック",
  "Load File": "ファイルを開く",
  "Use Sample Target": "サンプル対象を使用",
  "Apply to Current": "現在の対象へ適用",
  "Choose a recipe in Effect Library, then Apply to Current.": "エフェクトライブラリでレシピを選び、現在の対象へ適用してください。",
  "Live effect pages": "ライブエフェクトのページ",
  "Live effects": "ライブエフェクト",
  "Chaser effect editor": "チェイサーエフェクトエディター",
  "Move effect editor": "ムーブエフェクトエディター",
  "Move effect controls": "ムーブエフェクト操作",
  "Move FX": "ムーブFX",
  "Move path editor": "ムーブパスエディター",
  "Move path modes": "ムーブパスモード",
  "Move path point operations": "ムーブパスのポイント操作",
  "Move path points": "ムーブパスのポイント",
  "Move path recipe presets": "ムーブパスのレシピプリセット",
  "Move path recipes": "ムーブパスのレシピ",
  "Move (Pan/Tilt path)": "ムーブ（Pan/Tiltパス）",
  "Move transport and clock": "ムーブのトランスポートとクロック",
  "Move transform": "ムーブのトランスフォーム",
  "Move direction": "ムーブ方向",
  "Move coordinate mode": "ムーブ座標モード",
  "Move interpolation": "ムーブ補間",
  "Move clock sync presets": "ムーブのクロック同期プリセット",
  "Move phase percent": "ムーブ位相（パーセント）",
  "Move phase percent value": "ムーブ位相（パーセント）の値",
  "Move fixture spread percent": "ムーブのフィクスチャー分散（パーセント）",
  "Move fixture spread percent value": "ムーブのフィクスチャー分散（パーセント）の値",
  "Move point earlier": "ムーブポイントを前へ",
  "Move point later": "ムーブポイントを後へ",
  "Value FX": "バリューFX",
  "Value (envelope)": "バリュー（エンベロープ）",
  "Value effect editor": "バリューエフェクトエディター",
  "Value envelope point operations": "バリューエンベロープのポイント操作",
  "Value envelope points": "バリューエンベロープのポイント",
  "Value mode": "バリューモード",
  "Value interpolation": "バリュー補間",
  "Value direction": "バリュー方向",
  "Value clock sync presets": "バリューのクロック同期プリセット",
  "Value phase percent": "バリュー位相（パーセント）",
  "Value phase percent value": "バリュー位相（パーセント）の値",
  "Value fixture spread percent": "バリューのフィクスチャー分散（パーセント）",
  "Value fixture spread percent value": "バリューのフィクスチャー分散（パーセント）の値",
  Envelope: "エンベロープ",
  "Position / Value": "位置 / 値",
  Pos: "位置",
  Val: "値",
  "Double-click to add · drag points · Arrow keys nudge · Shift coarse · Alt fine · Delete remove":
    "ダブルクリックで追加 · ポイントをドラッグ · 矢印キーで微調整 · Shiftで粗く · Altで細かく · Deleteで削除",
  Forward: "順方向",
  Reverse: "逆方向",
  Absolute: "絶対",
  Relative: "相対",
  Smooth: "スムーズ",
  Free: "フリー",
  "Closed path": "閉じたパス",
  "Open path": "開いたパス",
  "Path points": "パスポイント",
  "Point operations": "ポイント操作",
  "Path recipe": "パスレシピ",
  "Add point": "ポイントを追加",
  "Add first point": "最初のポイントを追加",
  "Remove point": "ポイントを削除",
  "Add a point to define the movement path.": "動作パスを定義するポイントを追加してください。",
  "Control path": "制御パス",
  "Output preview": "出力プレビュー",
  "Double-click grid to add · Arrow keys nudge · Shift coarse · Alt fine · Home center · Delete remove":
    "グリッドをダブルクリックで追加 · 矢印キーで微調整 · Shiftで粗く · Altで細かく · Homeで中央 · Deleteで削除",
  Closed: "閉じたパス",
  Coordinates: "座標",
  "Custom path loaded": "カスタムパスを読み込み済み",
  Direction: "方向",
  Spread: "分散",
  "Phase / Spread": "位相 / 分散",
  "Translate / Scale / Rotate": "移動 / 拡縮 / 回転",
  "Translate X": "移動 X",
  "Translate Y": "移動 Y",
  "Rotate °": "回転 °",
  "points /": "ポイント /",
  "X / Y ·": "X / Y ・",
  "Chase preview": "チェイスプレビュー",
  "Add a target to build Chaser steps.": "対象を追加してチェイサーのステップを作成してください。",
  "Chase flow": "チェイス動作",
  "Chaser direction": "チェイサーの方向",
  "One way only": "一方向のみ",
  "first to last": "先頭から末尾",
  "last to first": "末尾から先頭",
  "return pass": "往復",
  "seeded order": "シード固定順",
  "Pixels on": "点灯ピクセル数",
  "Wings": "ウィング数",
  "Size": "サイズ",
  "Chaser size percent": "チェイサーのサイズ（パーセント）",
  "Chaser fixture spread percent": "チェイサーのフィクスチャー分散（パーセント）",
  "Fading": "フェード",
  "Fade overlap": "フェードの重なり",
  "Chaser fade overlap percent": "チェイサーのフェード重複（パーセント）",
  "Random seed": "ランダムシード",
  "Step clock": "ステップクロック",
  "Step ms": "ステップ時間 ms",
  "Chaser clock sync presets": "チェイサーのクロック同期プリセット",
  "Features": "フィーチャー",
  "Chaser feature ranges": "チェイサーのフィーチャー範囲",
  "Add feature": "フィーチャーを追加",
  "Move feature up": "フィーチャーを上へ移動",
  "Move feature down": "フィーチャーを下へ移動",
  "Remove feature": "フィーチャーを削除",
  "Beam order": "ビーム順序",
  "Current target": "現在の対象",
  "Append current": "現在の対象を追加",
  "Add gap": "空ステップを追加",
  "Replace with current target": "現在の対象で置換",
  "Chaser beam steps": "チェイサーのビームステップ",
  "Move step up": "ステップを上へ移動",
  "Move step down": "ステップを下へ移動",
  "Remove step": "ステップを削除",
  "Chaser step pages": "チェイサーステップのページ",
  "One fixture per step preserves the patched beam order.": "1ステップにつき1フィクスチャーにすると、パッチ順のビーム順序を保持できます。",
  steps: "ステップ",
  feature: "フィーチャー",
  on: "点灯",
  phase: "位相",
  "pixels on ·": "点灯ピクセル ·",
  "% size": "% サイズ",
  "visible /": "表示 /",
  "/ 16 features": "/ 16 フィーチャー",
  "Move up": "上へ移動",
  "Move down": "下へ移動",
  More: "その他",
  "Add Effect": "エフェクトを追加",
  "Clip and transition desk": "クリップとトランジションデスク",
  Clips: "クリップ",
  "AUTO VJ": "自動VJ",
  "Deterministic Auto VJ director": "決定論的Auto VJディレクター",
  "Auto VJ beats per change": "Auto VJの切替間隔（ビート）",
  "Auto VJ pulses per change": "Auto VJの切替間隔（入力パルス）",
  "Auto VJ transition duration": "Auto VJのトランジション時間",
  "Auto VJ deterministic seed": "Auto VJの決定論的シード",
  "Auto VJ rhythm source": "Auto VJのリズムソース",
  "Choose clips eligible for automatic Takes": "自動テイク対象のクリップを選択",
  "Disarm Auto VJ to edit configuration": "設定を編集するにはAuto VJを解除してください",
  "Use all clips": "全クリップを使用",
  "No repeat": "連続リピートなし",
  "Not set": "未設定",
  "Add a video clip to enable Auto VJ": "Auto VJを有効にするには映像クリップを追加してください",
  "Add a video clip to enable Auto VJ.": "Auto VJを有効にするには映像クリップを追加してください。",
  "Add at least one video clip before configuring Auto VJ.": "Auto VJを設定する前に映像クリップを1つ以上追加してください。",
  "Waiting for a quantized boundary": "クオンタイズ境界を待機中",
  Arm: "有効化",
  Disarm: "解除",
  Hold: "ホールド",
  Resume: "再開",
  Armed: "待機",
  Running: "実行中",
  Fault: "異常",
  Rhythm: "リズム",
  Change: "切替",
  Transition: "トランジション",
  Seed: "シード",
  CLOCK: "クロック",
  "LIVE INPUT": "ライブ入力",
  available: "利用可能",
  "LIVE TAKE": "ライブテイク",
  "Program monitor and outputs": "プログラムモニターと出力",
  "Program Monitor": "プログラムモニター",
  "Reference preview": "参照プレビュー",
  "Live Monitors": "ライブモニター",
  "Live video monitors": "ライブ映像モニター",
  "Staged clip and routed output": "待機クリップとルーティング出力",
  "PREVIEW / PROGRAM": "プレビュー / プログラム",
  "Preview transport": "プレビュートランスポート",
  "PREVIEW TRANSPORT": "プレビュートランスポート",
  "Preview position": "プレビュー位置",
  "Preview speed": "プレビュー速度",
  "Decrease preview speed": "プレビュー速度を下げる",
  "Independent Preview supports local video and still image layers": "独立Previewはローカル動画と静止画レイヤーに対応します",
  "Increase preview speed": "プレビュー速度を上げる",
  "TO PROGRAM": "プログラムへ",
  "Transfer staged preview to Program": "待機中のプレビューをプログラムへ送る",
  "Desktop required — preview transport is unavailable in the browser fixture.": "デスクトップ版が必要です。ブラウザ用表示ではプレビュートランスポートを操作できません。",
  "Play preview": "プレビューを再生",
  "Pause preview": "プレビューを一時停止",
  "Staging preview…": "プレビューへ送信中…",
  "P buttons stage a clip without taking it live.": "Pボタンは本番出力を変えずにクリップをプレビューへ送ります。",
  "LOOP —": "ループ —",
  "LOOP OFF": "ループ OFF",
  "Staged clip": "待機クリップ",
  "Selected output": "選択中の出力",
  "Select an output": "出力を選択",
  "No video source": "映像ソースなし",
  Starting: "起動中",
  Paused: "一時停止中",
  "Monitor offline": "モニター停止中",
  "Open the desktop app for live video.": "ライブ映像を表示するにはデスクトップアプリで開いてください。",
  "Monitor paused outside the VJ desk.": "VJデスク以外ではモニターを一時停止します。",
  "The last frame is preserved while the monitor retries.": "モニターの再試行中は最後のフレームを保持します。",
  "Stage a clip with its P button.": "Pボタンでクリップをプレビュー待機にしてください。",
  "Waiting for a program source.": "プログラムソースを待機中です。",
  "Live preview monitor": "ライブプレビューモニター",
  "Live program monitor": "ライブプログラムモニター",
  "PREVIEW live video monitor": "プレビューのライブ映像モニター",
  "PROGRAM live video monitor": "プログラムのライブ映像モニター",
  "Retry monitors": "モニターを再試行",
  busy: "処理待ち",
  PROGRAM: "プログラム",
  "Live video layers": "ライブ映像レイヤー",
  "in composition": "コンポジション内",
  COMPOSITE: "コンポジット",
  "Audio & Capture": "音声と収録",
  "Audio &amp; Capture": "音声と収録",
  "Desktop required": "デスクトップ版が必要",
  Refresh: "更新",
  "Persistent show safety controls": "常設ショー安全操作",
  "Persistent workspace band": "常設ワークスペース帯",
  "active ·": "有効 ·",
  "stacked ·": "スタック ·",
  of: "／",
  recipes: "レシピ",
  Edit: "編集",
  Position: "位置",
  Color: "カラー",
  Beam: "ビーム",
  Dimmer: "ディマー",
  "No cue": "キューなし",
  "No recent projects": "最近使ったプロジェクトはありません",
  "Nothing to undo": "元に戻せる操作はありません",
  "Nothing to redo": "やり直せる操作はありません",
  "UI language": "UI言語",
  English: "英語",
  Japanese: "日本語",
  Remove: "削除",
  Fixtures: "灯体",
  Video: "映像",
  Duplicate: "複製",
  Reset: "リセット",
  Add: "追加",
  Cancel: "キャンセル",
  Next: "次へ",
  Prev: "前へ",
  Previous: "前へ",
  "Cue Page": "キューページ",
  "Previous cue page": "前のキューページ",
  "Next cue page": "次のキューページ",
  "Patched fixtures": "パッチ済み灯体",
  "Mapping fixtures": "マッピング灯体",
  Locked: "同期中",
  Stale: "同期切れ",
  Internal: "内部",
  LOCK: "同期",
  STALE: "同期切れ",
  INTERNAL: "内部",
  "Awaiting external sync": "外部同期を待機中",
  "Local clock": "内部クロック",
  "ms since sync": "ms（最終同期から）",
  Timecode: "タイムコード",
  Back: "戻る",
  Clear: "クリア",
  Browse: "参照",
  Copy: "コピー",
  Rename: "名前変更",
  "Set BPM": "BPMを設定",
  "Tap BPM": "タップBPM",
  "System default": "システム既定",
  "No fixture selected": "灯体が選択されていません",
  "Selected Fixture": "選択中の灯体",
  "No video outputs": "映像出力がありません",
  "Outputs / Sources": "出力 / ソース",
  configured: "設定済み",
  "Video setup tools": "映像セットアップツール",
  "Output Controls": "出力コントロール",
  "Configuration and live actions": "設定とライブ操作",
  "No presets": "プリセットがありません",
  "Select preset": "プリセットを選択",
  "DMX Routes": "DMX経路",
  "DMX Output": "DMX出力",
  "DMX Blackout": "DMXブラックアウト",
  "All Blackout": "全ブラックアウト",
  "Video Blackout": "映像ブラックアウト",
  "Lighting Master": "照明マスター",
  "Group Submaster": "グループサブマスター",
  Submasters: "サブマスター",
  Lighting: "照明",
  Fixture: "灯体",
  "Fixture Attribute": "灯体属性",
  "Fixture Highlight": "灯体ハイライト",
  "Fixture Solo": "灯体ソロ",
  "Fixture Park": "灯体パーク",
  "Group Highlight": "グループハイライト",
  "Group Solo": "グループソロ",
  "Group Park": "グループパーク",
  "Clear Fixture Flags": "灯体フラグをクリア",
  "Movement Limits": "ムーブメント制限",
  "Dimmer Limits": "ディマー制限",
  "Reset Movement": "ムーブメントをリセット",
  "Trigger Cue": "キューを実行",
  "Cue Next": "次のキュー",
  "Cue Previous": "前のキュー",
  "Cue Fade Pause": "キューフェード一時停止",
  "Cue Pads": "キューパッド",
  Cue: "キュー",
  Palette: "パレット",
  Palettes: "パレット",
  Programmer: "プログラマー",
  Preview: "プレビュー",
  Program: "プログラム",
  Active: "アクティブ",
  Primary: "プライマリ",
  Runtime: "ランタイム",
  Transport: "トランスポート",
  Trigger: "実行",
  Step: "ステップ",
  Time: "時間",
  Speed: "速度",
  Opacity: "不透明度",
  Rotation: "回転",
  Transform: "変形",
  Brightness: "明るさ",
  Contrast: "コントラスト",
  Saturation: "彩度",
  Hue: "色相",
  Gamma: "ガンマ",
  Blur: "ぼかし",
  Glow: "グロー",
  Edge: "エッジ",
  Pixelate: "ピクセル化",
  Linear: "線形",
  Bezier: "ベジェ",
  Circle: "円",
  Triangle: "三角波",
  Random: "ランダム",
  Radial: "放射状",
  Multiply: "乗算",
  High: "高域",
  Mid: "中域",
  Bass: "低域",
  Waveform: "波形",
  "Timeline Play": "タイムライン再生",
  "Timeline Seek": "タイムライン移動",
  "Timeline Automation": "タイムラインオートメーション",
  "Timeline Analysis": "タイムライン解析",
  Playhead: "再生位置",
  "Video Control": "映像コントロール",
  "Video Setup": "映像セットアップ",
  "Video Layers": "映像レイヤー",
  "Video Outputs": "映像出力",
  "Video Output Config": "映像出力設定",
  "Video Output Enable": "映像出力を有効化",
  "Video Output Blackout": "映像出力ブラックアウト",
  "Video Output Opacity": "映像出力の不透明度",
  "Video Output Fade": "映像出力フェード",
  "Video Output Mapping Field": "映像出力マッピング項目",
  "Video Output Mapping Preset": "映像出力マッピングプリセット",
  "Video Layer Enable": "映像レイヤーを有効化",
  "Video Layer Solo": "映像レイヤーソロ",
  "Video Layer Fade": "映像レイヤーフェード",
  "Video Play": "映像再生",
  "Video Param": "映像パラメータ",
  "Video Position": "映像位置",
  "Video Only": "映像のみ",
  "Video file": "映像ファイル",
  "Video A-B Loop": "映像A-Bループ",
  "Add Cue Point": "キューポイントを追加",
  "Video Cue Point Add": "映像キューポイント追加",
  "Video Cue Point Remove": "映像キューポイント削除",
  "Video Cue Point Jump": "映像キューポイントへ移動",
  "Video Cue Point Next": "次の映像キューポイント",
  "Video Cue Point Previous": "前の映像キューポイント",
  "Node Graph Enable": "ノードグラフを有効化",
  "Effect Enable": "エフェクトを有効化",
  "Effect Recall": "エフェクト呼び出し",
  "Effects Only": "エフェクトのみ",
  "All Sources": "すべてのソース",
  "Effect Recall selection tools": "エフェクト呼び出し対象の選択ツール",
  "Cue Effect Recall targets": "キューのエフェクト呼び出し対象",
  "Included Effects recall their stored ON/OFF state on GO. Effects not listed here are left unchanged.":
    "対象に含めたエフェクトはGO時に保存済みのON/OFF状態を呼び出します。含めていないエフェクトは変更しません。",
  "Select All": "全て選択",
  "Capture Current": "現在状態を取得",
  "Refresh States": "状態を再取得",
  "Filter Effects": "エフェクトを絞り込み",
  "Name, ID, or type": "名前、ID、種類",
  "Effect Recall pages": "エフェクト呼び出しページ",
  "Previous Effect Recall page": "前のエフェクト呼び出しページ",
  "Next Effect Recall page": "次のエフェクト呼び出しページ",
  "No Effects match this filter.": "絞り込み条件に一致するエフェクトはありません。",
  "Create an Effect in the Effect rack first.": "先にエフェクトラックでエフェクトを作成してください。",
  "No Effects match this Cue scope.": "このキュー範囲に一致するエフェクトはありません。",
  "Save Recall stores only this Effect Recall list, including an empty list when the Cue still has another target.":
    "呼び出しを保存では、このエフェクト呼び出しリストだけを保存します。キューに別のターゲットがあれば空のリストも保存できます。",
  "Update Look recaptures the current Store Scope:": "ルックを更新すると、現在の保存範囲を再取得します:",
  "It does not save Recall edits.": "呼び出し設定の編集内容は保存しません。",
  "A Cue needs at least one target. Remove this Cue instead of saving an empty Effect-only Recall.":
    "キューには1つ以上のターゲットが必要です。エフェクト専用の呼び出しを空で保存せず、このキューを削除してください。",
  "Press Update to store Effect Recall edits with the Cue.": "更新を押すと、エフェクト呼び出し設定をキューへ保存します。",
  "Only Effects matching this Cue scope are listed. Mixed Lighting/Video Effects appear in both scopes.":
    "このキュー範囲に一致するエフェクトだけを表示します。照明と映像の両方を対象にするエフェクトは、両方の範囲に表示されます。",
  "Effects Only updates Effect Recall while preserving every other target already stored in this Cue.":
    "エフェクトのみで更新すると、このキューに保存済みの他の全ターゲットを維持したままエフェクト呼び出しだけを更新します。",
  "Position Wave": "位置ウェーブ",
  "Projection Mapping": "プロジェクションマッピング",
  "Projection Surfaces": "投影面",
  "Stage Center": "ステージ中央",
  "Position Favorites": "位置のお気に入り",
  "Reset Transform": "変形をリセット",
  "Use Draft": "下書きを使用",
  "Use Auto": "自動設定を使用",
  "Web Remote": "Webリモート",
  "Remote URLs": "リモートURL",
  "New PIN": "新しいPIN",
  "Load Mapping": "マッピングを開く",
  "Save Mapping": "マッピングを保存",
  Mappings: "マッピング",
  Selections: "選択",
  Grid: "グリッド",
  Label: "ラベル",
  Display: "ディスプレイ",
  Window: "ウィンドウ",
  "Workspace Layout": "ワークスペース配置",
  "Tabs and desk surfaces auto-save on this device": "タブとデスク面はこの端末へ自動保存されます",
  Sample: "サンプル",
  "Phase 1 Smoke": "Phase 1スモーク",
  "Overall budget": "総合性能予算",
  "Review before patching this profile.": "このプロファイルを確認してからパッチしてください。",
  "Patch fixtures or adjust filters.": "灯体をパッチするかフィルターを調整してください。",
  "This shader has no operator controls.": "このシェーダーに操作パラメータはありません。",
  "Interface scale": "表示倍率",
  "Created new untitled project.": "新しい未保存プロジェクトを作成しました。",
  "New project canceled.": "新規プロジェクト作成をキャンセルしました。",
  "Project save canceled.": "プロジェクト保存をキャンセルしました。",
  "Project load canceled.": "プロジェクト読込をキャンセルしました。",
  "Template save canceled.": "テンプレート保存をキャンセルしました。",
  "Template load canceled.": "テンプレート読込をキャンセルしました。",
  "No recovery checkpoint is available.": "利用できる復旧チェックポイントはありません。",
  "Recovery checkpoint discarded.": "復旧チェックポイントを破棄しました。",
  "Project backup restore canceled.": "バックアップ復元をキャンセルしました。",
  "Audio analysis canceled.": "音声解析をキャンセルしました。",
  "Cleared audio analysis.": "音声解析をクリアしました。",
  All: "全て",
  Output: "出力",
  Rotate: "回転",
  Attribute: "属性",
  "Clear Flags": "フラグをクリア",
  Down: "下",
  "Fade ms": "フェード ms",
  Kind: "種類",
  Layer: "レイヤー",
  Pattern: "パターン",
  Port: "ポート",
  Start: "開始",
  Universe: "ユニバース",
  Up: "上",
  Width: "幅",
  Yaw: "ヨー",
  "Bind IP": "待受IP",
  Curve: "カーブ",
  End: "終了",
  From: "開始",
  Mode: "モード",
  Rot: "回転",
  Solo: "ソロ",
  to: "から",
  To: "終了",
  Address: "アドレス",
  "All BO": "全BO",
  "All Clear": "全消去",
  Apply: "適用",
  Aspect: "アスペクト",
  "Clear Lens/Key": "レンズ／キーをクリア",
  "Clear Warp": "ワープをクリア",
  "Fade Out": "フェードアウト",
  Group: "グループ",
  Groups: "グループ",
  In: "入力",
  Key: "キー",
  Lens: "レンズ",
  Level: "レベル",
  Max: "最大",
  Min: "最小",
  Name: "名前",
  "Node Graph": "ノードグラフ",
  "0.00–1.00 normalized": "0.00〜1.00 正規化",
  "Attack ms": "アタック ms",
  "Audio feature input level": "音声特徴量の入力レベル",
  "Engine audio feature input level": "エンジン音声特徴量の入力レベル",
  "Engine audio mapping output": "エンジン音声マッピング出力",
  "Engine runtime · node": "エンジン実行値 · ノード",
  "Audio mapping output preview": "音声マッピング出力プレビュー",
  "Audio mapping signal path": "音声マッピング信号経路",
  "Audio Reactive": "オーディオリアクティブ",
  "Audio reactive live rack": "オーディオリアクティブ・ライブラック",
  "Audio reactive mapping controls": "オーディオリアクティブ・マッピング操作",
  "Band 1–16": "バンド 1〜16",
  Bias: "バイアス",
  "Create Mapping": "マッピングを作成",
  Dynamics: "ダイナミクス",
  "Edit Rack": "ラックを編集",
  Exponential: "指数",
  Feature: "特徴量",
  Feed: "入力元",
  "FFT band": "FFTバンド",
  Gain: "ゲイン",
  Gate: "ゲート",
  "Hold ms": "ホールド ms",
  IN: "入力",
  Input: "入力",
  "Invert output": "出力を反転",
  Logarithmic: "対数",
  "No audio mappings": "音声マッピングなし",
  "No saved mapping": "保存済みマッピングなし",
  "Monitor mapping": "監視するマッピング",
  "Open Audio Reactive Rack": "オーディオリアクティブ・ラックを開く",
  "Open Rack": "ラックを開く",
  OUT: "出力",
  REACTIVE: "リアクティブ",
  "Release ms": "リリース ms",
  Smoothstep: "スムーズステップ",
  "SAVE TO MONITOR": "保存後に監視可能",
  DISABLED: "無効",
  READY: "準備完了",
  "SAFE ZERO": "安全ゼロ",
  HELD: "ホールド中",
  OFF: "OFF",
  Nudge: "微調整",
  "Output Ratio": "出力比率",
  Param: "パラメータ",
  Park: "パーク",
  Pitch: "ピッチ",
  Roll: "ロール",
  Route: "経路",
  Source: "ソース",
  Tap: "タップ",
  "2D fixture and projection surface mapping stage": "灯体と投影面の2Dマッピングステージ",
  "2D Mapping": "2Dマッピング",
  Action: "操作",
  "Add a keyframe at the current playhead": "現在の再生位置へキーフレームを追加",
  Align: "整列",
  "All On": "全てON",
  "Apply Output": "出力へ適用",
  "At Playhead": "再生位置へ",
  Beat: "ビート",
  "Beat Next": "次のビート",
  "Beat Previous": "前のビート",
  Blend: "ブレンド",
  "BPM Loop Bars": "BPMループ小節",
  "BPM Sync": "BPM同期",
  "BPM Sync Ratio": "BPM同期比率",
  Channel: "チャンネル",
  "Clear Corners": "コーナーをクリア",
  "Clear flags": "フラグをクリア",
  Count: "数",
  "Cue List": "キューリスト",
  "Cue point index": "キューポイント番号",
  "Del Key": "Deleteキー",
  "Delay ms": "ディレイ ms",
  Depth: "深度",
  Disconnect: "切断",
  Effect: "エフェクト",
  Enabled: "有効",
  Endpoint: "エンドポイント",
  Export: "書き出し",
  "Fade In": "フェードイン",
  First: "先頭",
  Flash: "フラッシュ",
  Fullscreen: "全画面",
  Geometry: "ジオメトリ",
  "Group ID": "グループID",
  Height: "高さ",
  Import: "読み込み",
  Inherit: "継承",
  Invert: "反転",
  "Invert Pan": "Pan反転",
  "Invert Tilt": "Tilt反転",
  Learn: "学習",
  Left: "左",
  Light: "照明",
  Line: "線",
  List: "リスト",
  Loop: "ループ",
  "Loop in": "ループ開始",
  "Loop out": "ループ終了",
  Low: "低",
  "Mapping Field": "マッピング項目",
  "Mapping Preset": "マッピングプリセット",
  Monitor: "モニター",
  Move: "移動",
  "Move draft start to the current playhead": "下書きの開始を現在の再生位置へ移動",
  Mute: "ミュート",
  Number: "番号",
  Objects: "オブジェクト",
  Open: "開く",
  "Pairing PIN": "ペアリングPIN",
  "Pan Max": "Pan最大",
  "Pan Min": "Pan最小",
  "Pan tilt movement limits": "Pan／Tiltムーブメント制限",
  "Pick Visible": "表示中を選択",
  Preset: "プリセット",
  Protocol: "プロトコル",
  Ratio: "比率",
  "Refresh audio output devices": "音声出力デバイスを更新",
  "Refresh serial ports": "シリアルポートを更新",
  "Remove the keyframe nearest to the current playhead": "現在位置に最も近いキーフレームを削除",
  "Reset Pose": "姿勢をリセット",
  "Reset Stage": "ステージをリセット",
  Resize: "サイズ変更",
  Right: "右",
  "Save Preset": "プリセットを保存",
  Scope: "範囲",
  Search: "検索",
  Seek: "移動",
  Sel: "選択",
  Select: "選択",
  "Select this video output for stage mapping and live preview": "この映像出力をステージマッピングとライブプレビューへ選択",
  "Serial port": "シリアルポート",
  Set: "設定",
  Shape: "形状",
  Snap: "スナップ",
  Stage: "ステージ",
  "Stage Object": "ステージオブジェクト",
  "Start Remote": "リモート開始",
  Stop: "停止",
  "Stop Remote": "リモート停止",
  Surfaces: "投影面",
  Swap: "入替",
  Sync: "同期",
  "Sync Pattern": "同期パターン",
  Target: "対象",
  "Tilt Max": "Tilt最大",
  "Tilt Min": "Tilt最小",
  Track: "トラック",
  Lane: "レーン",
  "Light lane visibility": "照明レーンの表示",
  "Video lane visibility": "映像レーンの表示",
  "Video Layer": "映像レイヤー",
  View: "表示",
  "2D map fixture flags": "2Dマップ灯体フラグ",
  "2D mapping keyboard shortcuts": "2Dマッピングのキーボード操作",
  "2D mapping tools": "2Dマッピングツール",
  "2D mapping viewport": "2Dマッピング表示領域",
  "A/B Mix": "A/Bミックス",
  "A/V drift": "A/Vずれ",
  Abs: "絶対値",
  "Active / Standby": "アクティブ／スタンバイ",
  "Active cue": "実行中キュー",
  "Add Attribute": "属性を追加",
  "Add Center": "中央へ追加",
  "Add Composition": "コンポジションを追加",
  "Add Cue Part": "キューパートを追加",
  "Add Current": "現在値を追加",
  "Add Event": "イベントを追加",
  "Add Fader": "フェーダーを追加",
  "Add Inside": "内側を追加選択",
  "Add Mapping": "マッピングを追加",
  "Add OSC Mapping": "OSCマッピングを追加",
  "Add Output": "出力を追加",
  "Add Video": "映像を追加",
  "Add Video Layer": "映像レイヤーを追加",
  "Additional color channel sliders": "追加カラーチャンネルスライダー",
  "Addr Step": "アドレス間隔",
  "Align X": "X方向へ整列",
  "Align Z": "Z方向へ整列",
  "All Types": "全種類",
  Amount: "量",
  "Analyze Audio": "音声を解析",
  Applied: "適用済み",
  "Apply BPM": "BPMを適用",
  "Apply Groups": "グループを適用",
  "Apply Limits": "制限を適用",
  "Apply Patch": "パッチを適用",
  "Apply Preset": "プリセットを適用",
  "Apply Routes": "経路を適用",
  "Apply View": "表示を適用",
  "Arm standby outputs?": "スタンバイ出力を有効にしますか？",
  "Art-Net gateway": "Art-Netゲートウェイ",
  "Aspect Mode": "アスペクトモード",
  Attrs: "属性",
  Audio: "音声",
  "All → mono": "全チャンネル → モノ",
  "→ mono": "→ モノ",
  "Audio input": "音声入力",
  "Audio input backend": "音声入力バックエンド",
  "Audio input channel mix": "音声入力チャンネルミックス",
  "Audio input requested buffer frames": "音声入力要求バッファフレーム",
  "Audio input sample rate": "音声入力サンプルレート",
  Buffer: "バッファ",
  "Buffer default": "バッファ既定",
  Ch: "チャンネル",
  "Ch 1+2 → mono": "チャンネル1+2 → モノ",
  frames: "フレーム",
  Mix: "ミックス",
  Rate: "レート",
  "Rate auto": "レート自動",
  "Audio Band": "音声帯域",
  "Audio Bias": "音声バイアス",
  "Audio device": "音声デバイス",
  "Audio FFT": "音声FFT",
  "Audio FFT bass mid high over time": "音声FFTの低域・中域・高域推移",
  "Audio Gain": "音声ゲイン",
  "Audio Input": "音声入力",
  Auto: "自動",
  "Auto feedback": "自動フィードバック",
  "Auto Fit": "自動フィット",
  "Auto White": "自動ホワイト",
  Backends: "バックエンド",
  Bar: "小節",
  Bars: "小節",
  "Baud rate": "ボーレート",
  Beams: "ビーム",
  Bits: "ビット",
  "Black Level": "ブラックレベル",
  "fixture(s)": "灯体",
  "attribute(s)": "属性",
  "node(s)": "ノード",
  "control(s)": "コントロール",
  "video output(s)": "映像出力",
  "video layer(s) /": "映像レイヤー /",
  "universe(s)": "ユニバース",
  picked: "選択済み",
  shown: "表示中",
  active: "有効",
  auto: "自動",
  beat: "ビート",
  step: "ステップ",
  keys: "キー",
  "corner pin": "コーナーピン",
  "front, movers": "フロント、ムーバー",
  "on,": "ON、",
  ". Arrow keys nudge, Shift coarse, Alt fine, Home reset.": ". 矢印キーで微調整、Shiftで大きく、Altで細かく、Homeでリセット。",
  ". Arrow keys nudge, Shift coarse, Alt fine, Home/End jump.": ". 矢印キーで微調整、Shiftで大きく、Altで細かく、Home／Endで移動。",
  "Arrow keys move limits, PageUp/+ expands, PageDown/- shrinks, Shift coarse, Alt fine, Home reset.":
    "矢印キーで制限を移動、PageUp／+で拡大、PageDown／-で縮小、Shiftで大きく、Altで細かく、Homeでリセット。",
  "Add fixtures inside the selected stage object to the current pick (Shift+I)":
    "選択中のステージオブジェクト内にある灯体を現在の選択へ追加（Shift+I）",
  "Align selected fixtures on X (X)": "選択した灯体をX方向へ整列（X）",
  "Align selected fixtures on Z (Z)": "選択した灯体をZ方向へ整列（Z）",
  "0 uses the selected profile footprint as the spacing.": "0では選択プロファイルの占有チャンネル数を間隔に使用します。",
  Out: "出力",
  Place: "配置",
  "fixture(s) /": "灯体 /",
  "effect(s) /": "エフェクト /",
  yaw: "ヨー",
  Blind: "ブラインド",
  Bottom: "下",
  "Blend Gamma": "ブレンドガンマ",
  Bright: "明",
  "Effect families": "エフェクト系統",
  Colour: "カラー",
  Chaser: "チェイサー",
  "Colour Mappings": "カラーマッピング",
  "Curve Saw": "カーブ・ノコギリ波",
  "Colour Spectrum": "カラースペクトラム",
  "Colour Chase": "カラーチェイス",
  "Color effect editor": "カラーエフェクトエディター",
  "Palette stops": "パレットストップ",
  "Color palette stops": "カラーパレットストップ",
  "/ 8 stops": "/ 8ストップ",
  spread: "スプレッド",
  "Color flow": "カラーフロー",
  Algorithm: "アルゴリズム",
  Interpolation: "補間",
  Cycle: "サイクル",
  Bounce: "バウンス",
  Sequence: "シーケンス",
  "HSV shortest": "HSV 最短経路",
  "HSV longest": "HSV 最長経路",
  "Fixture spread": "灯体スプレッド",
  "Fixture color phase spread": "灯体カラー位相スプレッド",
  "Fixture color phase spread percent": "灯体カラー位相スプレッド（%）",
  "Color effect clock sync presets": "カラーエフェクトのクロック同期プリセット",
  "Move stop up": "ストップを上へ移動",
  "Move stop down": "ストップを下へ移動",
  "Remove stop": "ストップを削除",
  "Add stop": "ストップを追加",
  "Multi-color": "マルチカラー",
  "MULTI-COLOR": "マルチカラー",
  "Prepared a multi-color draft for whole-fixture colour output.":
    "灯体全体のカラー出力用マルチカラー案を準備しました。",
  "RGB / RGBW / Wheel": "RGB / RGBW / ホイール",
  "Fixture order": "灯体順",
  "A color effect requires 2 to 8 palette stops.": "カラーエフェクトには2〜8個のパレットストップが必要です。",
  "Palette colors and positions must be within range.": "パレットの色と位置を有効範囲内に設定してください。",
  "Each palette stop needs a unique position.": "各パレットストップには重複しない位置が必要です。",
  "Color effects require 2 to 8 ordered palette stops with valid colors.":
    "カラーエフェクトには、有効な色を持つ位置順のパレットストップが2〜8個必要です。",
  "Seven-stop HSV spectrum rendered across the fixture's complete colour system.":
    "灯体のカラーシステム全体へ出力する7ストップHSVスペクトラムです。",
  "Ordered multi-colour steps spread deterministically across the current fixtures.":
    "現在の灯体へ決定的な順序で展開するマルチカラーステップです。",
  "Any value": "任意の値",
  "Colour attribute": "カラー属性",
  "Beat-synced saw curve for ramps, wheels and continuous channels.":
    "ランプ、ホイール、連続値チャンネル用のビート同期ノコギリ波です。",
  "Continuous spectrum sweep for hue, wheel or individual colour channels.":
    "Hue、カラーホイール、各色チャンネル用の連続スペクトラムスイープです。",
  "Position-mapped colour sweep across the current fixture layout.":
    "現在の灯体配置に沿って位置マッピングしたカラースイープです。",
  "This effect requires the current target": "このエフェクトには現在のターゲットが必要です",
  "Load the embedded sample target": "組み込みサンプルのターゲットへ読み込む",
  "Select a colour, hue, wheel, emitter, or video colour target.":
    "カラー、Hue、ホイール、発光色、または映像カラーのターゲットを選択してください。",
  "Built-in FX": "内蔵FX",
  "Add built-in FX": "内蔵FXを追加",
  "Add ISF": "ISFを追加",
  "Clear stack": "スタックをクリア",
  "ISF Stack": "ISFスタック",
  live: "稼働",
  "No FX in this stack.": "このスタックにはFXがありません。",
  "Another FX Event pulse is still active.": "別のFXイベントパルスが動作中です。",
  "Wait for the active FX Event pulse to finish.": "動作中のFXイベントパルスが完了するまで待ってください。",
  "Wait for the active FX Event pulse to finish before Undo.": "Undoする前にFXイベントパルスの完了を待ってください。",
  "Wait for the active FX Event pulse to finish before Redo.": "Redoする前にFXイベントパルスの完了を待ってください。",
  "Portable single-pass ISF stages stay embedded in the project and run as one GPU stack.":
    "可搬single-pass ISFはプロジェクトに埋め込まれ、1つのGPUスタックとして実行されます。",
  "Choose effect": "エフェクトを選択",
  "Import ISF": "ISFを読み込み",
  "Replace ISF": "ISFを差し替え",
  Bypassed: "バイパス",
  Advanced: "詳細",
  "FX error": "FXエラー",
  "Video output selection": "映像出力の選択",
  Colorize: "カラーライズ",
  "Glitch Shift": "グリッチシフト",
  Kaleidoscope: "カレイドスコープ",
  Mirror: "ミラー",
  "Manual protocol selection": "プロトコルを手動選択",
  Monochrome: "モノクローム",
  Posterize: "ポスタライズ",
  "RGB Split": "RGBスプリット",
  "Rhythm & Glitch": "リズム＆グリッチ",
  Scanlines: "スキャンライン",
  Strobe: "ストロボ",
  Vignette: "ビネット",
  "Use recommended protocol": "推奨プロトコルを使用",
  Zoom: "ズーム",
  "Browse Source": "ソースを参照",
  Bump: "バンプ",
  "Camera input": "カメラ入力",
  "Cancel Edit": "編集をキャンセル",
  Capture: "取得",
  "Capture a palette in the Programmer area first.": "先にプログラマー領域でパレットを取得してください。",
  "Category Actions": "カテゴリ操作",
  Center: "中央",
  "Channel Functions": "チャンネル機能",
  "Check Backends": "バックエンドを確認",
  "Check I/O": "I/Oを確認",
  "Check Plans": "プランを確認",
  "Check Windows": "ウィンドウを確認",
  Checkpoint: "チェックポイント",
  Clamp: "クランプ",
  "Clear Bitmap": "ビットマップをクリア",
  "Clear Blend": "ブレンドをクリア",
  "Clear fixture flags globally": "全灯体フラグをクリア",
  "Clear ISF": "ISFをクリア",
  "Clear Mask": "マスクをクリア",
  "Clear Pick": "選択をクリア",
  "Clear Picked": "選択済みをクリア",
  "Clear Port": "ポートをクリア",
  "Clear Programmer?": "プログラマーをクリアしますか？",
  "Clear Staged Values": "仮値をクリア",
  "Client #": "クライアント #",
  "Clip Bank": "クリップバンク",
  "Clip Grid": "クリップグリッド",
  Clock: "クロック",
  Close: "閉じる",
  "Close (Esc)": "閉じる（Esc）",
  "Close mapping shortcut help": "マッピング操作ヘルプを閉じる",
  "Close Open": "開くを閉じる",
  "Close Pattern": "パターンを閉じる",
  Command: "コマンド",
  Commit: "確定",
  Confirm: "確認",
  "Confirm Take Over": "テイクオーバーを確認",
  "Connect Feedback": "フィードバック接続",
  "Connect MIDI Clock / MTC": "MIDI Clock／MTC接続",
  "Connect MIDI Control": "MIDIコントロール接続",
  "Connected Clients": "接続中クライアント",
  "Control Active": "コントロール有効",
  "Control mode": "コントロールモード",
  "Control workspace": "コントロールワークスペース",
  "Control workspace header": "コントロールワークスペース見出し",
  "Controller UID": "コントローラーUID",
  Corners: "コーナー",
  Cosine: "コサイン",
  "Create Profile": "プロファイルを作成",
  "Crop bottom for": "下クロップ",
  "Crop left for": "左クロップ",
  "Crop right for": "右クロップ",
  "Crop top for": "上クロップ",
  "Cue In": "キュー入力",
  "Cue List executors": "キューリストエグゼキューター",
  "Cue List manager": "キューリスト管理",
  "Cue opacity": "キュー不透明度",
  Current: "現在",
  "Current Effect": "現在のエフェクト",
  "Custom Profile": "カスタムプロファイル",
  "Custom profile attribute templates": "カスタムプロファイル属性テンプレート",
  "Custom profile DMX map": "カスタムプロファイルDMXマップ",
  Cut: "カット",
  "Delete Object": "オブジェクトを削除",
  "Delete Preset": "プリセットを削除",
  "Delete this backup": "このバックアップを削除",
  "Delete View": "表示を削除",
  Disabled: "無効",
  "Disconnect Control": "コントロール切断",
  "Disconnect Feedback": "フィードバック切断",
  "Distribute selected fixtures on X (Shift+X)": "選択した灯体をX方向へ等間隔配置（Shift+X）",
  "Distribute selected fixtures on Z (Shift+Z)": "選択した灯体をZ方向へ等間隔配置（Shift+Z）",
  "Distribute X": "X方向へ等間隔配置",
  "Distribute Z": "Z方向へ等間隔配置",
  "DMX address page": "DMXアドレスページ",
  "DMX BO": "DMX BO",
  "DMX Clear": "DMXクリア",
  "DMX Footprint": "DMX占有数",
  "DMX Input / Merge": "DMX入力／マージ",
  "DMX Map": "DMXマップ",
  "DMX map view": "DMXマップ表示",
  "DMX output": "DMX出力",
  "DMX output enabled": "DMX出力有効",
  "DMX Patch Grid": "DMXパッチグリッド",
  "DMX Raw": "DMX生値",
  "DMX routes": "DMX経路",
  "DMX target": "DMX対象",
  "DMX Test Frame": "DMXテストフレーム",
  Download: "ダウンロード",
  "Drag any selected fixture to move the group.": "選択した灯体をドラッグするとグループ全体を移動できます。",
  Driver: "ドライバー",
  "Duplicate Fixture": "灯体を複製",
  Duration: "長さ",
  "Edge Blend / Black Level": "エッジブレンド／ブラックレベル",
  "Edit Map": "マップを編集",
  "Editable 2D stage map": "編集可能な2Dステージマップ",
  Editing: "編集中",
  "Effect waveform presets": "エフェクト波形プリセット",
  Empty: "空",
  "End address": "終了アドレス",
  Endpoints: "エンドポイント",
  "Engine Telemetry": "エンジンテレメトリ",
  "Export JSON": "JSONを書き出し",
  "Export SVG": "SVGを書き出し",
  Fade: "フェード",
  Faders: "フェーダー",
  Favorites: "お気に入り",
  Feather: "フェザー",
  File: "ファイル",
  Fill: "フィル",
  Fit: "フィット",
  "Fit All": "全体へフィット",
  "Fit Current": "現在対象へフィット",
  "Fit Object": "オブジェクトへフィット",
  "Fit Sel": "選択へフィット",
  "Fit selected items (Shift+F)": "選択項目へフィット（Shift+F）",
  "Fit visible stage items (F)": "表示中のステージ項目へフィット（F）",
  "Fixture flag quick filters": "灯体フラグのクイックフィルター",
  "Fixture groups": "灯体グループ",
  "Fixture selections": "灯体選択",
  "Fixture Setup": "灯体セットアップ",
  "Fixture UID": "灯体UID",
  fixtures: "灯体",
  "fixtures selected": "灯体を選択中",
  "Flip 180": "180度反転",
  Follow: "フォロー",
  "Follow ms": "フォロー ms",
  Footprint: "占有数",
  "Force Full Discovery": "完全ディスカバリーを強制",
  "Full Range": "全範囲",
  "Full Sat": "最大彩度",
  Fwd: "順方向",
  "Gateway FIFO": "ゲートウェイFIFO",
  "Gateway IP": "ゲートウェイIP",
  "GDTF Functions": "GDTF機能",
  "GDTF Geometry": "GDTFジオメトリ",
  "GDTF Share": "GDTF Share",
  Generation: "世代",
  GET: "GET",
  "Gobo Slots": "ゴボスロット",
  Graphs: "グラフ",
  "Green channel": "緑チャンネル",
  "Green Key": "グリーンキー",
  "Grid Cols": "グリッド列数",
  "Grid Here": "ここへグリッド配置",
  Heartbeat: "ハートビート",
  Highlight: "ハイライト",
  "HTP (highest wins)": "HTP（最大値優先）",
  "HTP MASTERS": "HTPマスター",
  "Hue and brightness pad": "色相・明るさパッド",
  "I/O Plans": "I/Oプラン",
  "IFCB timing overrides": "IFCBタイミング上書き",
  "Import Luma Mask": "輝度マスクを読み込み",
  "Import media to populate the clip grid.": "メディアを読み込むとクリップグリッドへ追加されます。",
  "Import Multiple": "複数読み込み",
  invalid: "無効",
  "Invert Hue": "色相を反転",
  "Invert mask": "マスクを反転",
  "ISF Shader": "ISFシェーダー",
  "Jump First": "先頭へ移動",
  "Keep Picked": "選択を保持",
  "Keyboard shortcut help": "キーボード操作ヘルプ",
  "Keyboard shortcut help (?)": "キーボード操作ヘルプ（?）",
  Labels: "ラベル",
  layer: "レイヤー",
  "layer(s)": "レイヤー",
  Layers: "レイヤー",
  Layout: "配置",
  "Lens Distortion": "レンズ歪み",
  "Level %": "レベル %",
  Levels: "レベル",
  "LFO clock": "LFOクロック",
  "LFO clock sync presets": "LFOクロック同期プリセット",
  "Lighting + Video": "照明＋映像",
  "Lighting automation rows": "照明オートメーション行",
  "Lighting Only": "照明のみ",
  "Lighting programmer": "照明プログラマー",
  Limits: "制限",
  "Line Here": "ここへ直線配置",
  "Line X": "X直線",
  "Link video layer": "映像レイヤーをリンク",
  "List label": "リスト名",
  Live: "ライブ",
  "Live audio analysis input": "ライブ音声解析入力",
  "Live audio frequency levels": "ライブ音声周波数レベル",
  "Live audio input device": "ライブ音声入力デバイス",
  "Live audio FFT levels": "ライブ音声FFTレベル",
  "Live audio status is unavailable. Stop remains available.":
    "ライブ音声の状態を取得できません。安全な停止操作は使用できます。",
  "Live audio status is unavailable. Start is locked.":
    "ライブ音声の状態を取得できないため、開始はロックされています。",
  "Live audio input stopped.": "ライブ音声入力は停止中です。",
  "Live audio input active.": "ライブ音声入力は動作中です。",
  "Live audio safety clear pending. Stop remains available.":
    "ライブ音声の安全クリアを待っています。停止操作は使用できます。",
  "Live audio Stop is waiting for the engine safety clear. Start is locked.":
    "ライブ音声の停止はエンジンの安全クリア待ちです。開始はロックされています。",
  "Live audio input stale. The engine accepted its zero-source clear request.":
    "ライブ音声入力が途絶しました。エンジンはゼロソースのクリア要求を受け付けました。",
  "Select a built audio input backend before Start.":
    "開始する前に、ビルド済みの音声入力バックエンドを選択してください。",
  "Select an ASIO driver before Start. Automatic driver selection is disabled.":
    "開始する前にASIOドライバを選択してください。ドライバの自動選択は無効です。",
  "Select an explicit ASIO sample rate and fixed buffer before Start.":
    "開始する前にASIOのサンプルレートと固定バッファを明示選択してください。",
  "Selected audio capture backend is not built into this application.":
    "選択した音声キャプチャバックエンドは、このアプリケーションに組み込まれていません。",
  "Live audio FFT input started.": "ライブ音声FFT入力を開始しました。",
  "Live audio FFT input stopped.": "ライブ音声FFT入力を停止しました。",
  "Resolve a supported live audio input configuration before Start.":
    "開始する前に、対応するライブ音声入力設定を確定してください。",
  "The previous audio input could not be identified safely after Refresh. Select an input again; Start is locked.":
    "更新後に以前の音声入力を安全に特定できませんでした。入力を選び直してください。開始はロックされています。",
  "Live Desk": "ライブデスク",
  "Live edit desk surface": "ライブ編集デスク面",
  "Live FFT input": "ライブFFT入力",
  "Live Input": "ライブ入力",
  "Load Graph": "グラフを開く",
  "Load Group Preset": "グループプリセットを開く",
  "Load Matching Preset": "一致プリセットを開く",
  "Load Preset": "プリセットを開く",
  "Load project (Ctrl/Cmd+O)": "プロジェクトを開く（Ctrl/Cmd+O）",
  "Load Selected": "選択項目を開く",
  "Load Target": "現在の対象へ読込",
  "Local Profile": "ローカルプロファイル",
  "Loss timeout ms": "信号消失タイムアウト ms",
  Maker: "メーカー",
  Manual: "手動",
  "Manual port": "手動ポート",
  "Manual UID": "手動UID",
  "Mapping Shortcuts": "マッピング操作",
  "Mark/MIB": "Mark／MIB",
  Master: "マスター",
  "Max Clients": "最大クライアント数",
  "Max Message KiB": "最大メッセージ KiB",
  "Max X": "X最大",
  "Max Z": "Z最大",
  Merge: "マージ",
  Message: "メッセージ",
  "Messages / sec": "メッセージ / 秒",
  "MIDI Control": "MIDIコントロール",
  "MIDI Feedback": "MIDIフィードバック",
  "Min X": "X最小",
  "Min Z": "Z最小",
  "Mini show": "ミニショー",
  "Mirror Pan": "Pan反転",
  "Mirror Tilt": "Tilt反転",
  "Mirror X": "X反転",
  "Mirror Z": "Z反転",
  "Monitor gain": "モニターゲイン",
  "Move Down": "下へ移動",
  "Move Up": "上へ移動",
  Multicast: "マルチキャスト",
  Neutral: "ニュートラル",
  "New Composition": "新しいコンポジション",
  "New List": "新しいリスト",
  "New Output": "新しい出力",
  "Next cue": "次のキュー",
  "Next Free": "次の空き",
  "Next Free A": "次の空きアドレス",
  "Next layer bank": "次のレイヤーバンク",
  "Next video output": "次の映像出力",
  No: "いいえ",
  None: "なし",
  "No backend status": "バックエンド状態なし",
  "No controls in this category.": "このカテゴリにコントロールはありません。",
  "No DMX controls.": "DMXコントロールはありません。",
  "No effects in the stack.": "エフェクトスタックは空です。",
  "No external routes": "外部経路なし",
  "No fixture types.": "灯体種類がありません。",
  "No fixtures": "灯体がありません",
  "No fixtures in group.": "グループに灯体がありません。",
  "No fixtures patched. Load a profile in Library, then use Patch Fixture.":
    "灯体がパッチされていません。ライブラリでプロファイルを開き、灯体をパッチしてください。",
  "No fixtures. Patch one in Setup &gt; Patch.": "灯体がありません。セットアップ > パッチで追加してください。",
  ". Apply targets": ". 対象を適用",
  "). Standby loading is fenced until only one remains.": "）。1台だけになるまでスタンバイ読込は遮断されます。",
  "/ Projection surface": "/ 投影面",
  "/ projection surface warp": "/ 投影面ワープ",
  "/ wavelength": "/ 波長",
  "+ Cue Point": "+ キューポイント",
  "active /": "有効 /",
  "Active in Setup / Mapping": "セットアップ／マッピングで有効",
  "Assign each fixture, video layer, or video output to one part. Lighting adds IFCB Delay; video holds until Part Delay. Blank Part Fade inherits the Cue Fade.":
    "各灯体、映像レイヤー、映像出力を1つのパートへ割り当てます。照明はIFCBディレイを加え、映像はパートディレイまで保持します。空のパートフェードはキューフェードを継承します。",
  attr: "属性",
  "attribute(s) with function ranges": "機能範囲付き属性",
  "Auto considers every fixture targeted by this Cue. Selecting fixtures limits MIB to that set; dark-only safety remains enforced.":
    "自動ではこのキューが対象とする全灯体を考慮します。灯体を選択するとMIBをその集合へ限定し、消灯時のみの安全条件は維持します。",
  "Blank Fade inherits the cue Fade. Delay holds the current value before that family starts.":
    "空のフェードはキューフェードを継承します。ディレイ中はその属性群が始まるまで現在値を保持します。",
  "Blue channel": "青チャンネル",
  "BPM sync": "BPM同期",
  bytes: "バイト",
  "Capture reads the current values from": "取得元の現在値:",
  "Checked palettes resolve their latest values on GO. Explicit values stored in this Cue take priority.":
    "チェックしたパレットはGOのたびに最新値を参照します。このキューへ明示保存した値が優先されます。",
  "Choose a local, UNC, or mounted shared folder": "ローカル、UNC、またはマウント済み共有フォルダーを選択",
  "Clear the current 2D mapping fixture pick (Ctrl+Shift+A)": "現在の2Dマッピング灯体選択をクリア（Ctrl+Shift+A）",
  "clip(s)": "クリップ",
  "consecutive failure(s)": "連続失敗",
  "controls.": "コントロール。",
  "Cue Parts (": "キューパート（",
  "Device Info PID": "デバイス情報PID",
  "Dimmer visual level": "ディマー表示レベル",
  "Disable every lighting automation row": "全照明オートメーション行を無効化",
  "Disable every video automation row": "全映像オートメーション行を無効化",
  "Discovered fixture (": "検出灯体（",
  drop: "ドロップ",
  "edge(s)": "エッジ",
  "Enable every lighting automation row": "全照明オートメーション行を有効化",
  "Enable every video automation row": "全映像オートメーション行を有効化",
  enabled: "有効",
  "Enter the gateway IP and discovered fixture UID. Replace the development controller UID with your assigned UID for production hardware.":
    "ゲートウェイIPと検出した灯体UIDを入力してください。本番機材では開発用コントローラーUIDを割り当て済みUIDへ置き換えてください。",
  "executor(s) · Page": "エグゼキューター · ページ",
  "Expected path: load mini show, trigger first cue, verify U0 A1-A8, video layer, and shared timeline probe.":
    "想定手順: ミニショーを開き、最初のキューを実行し、U0 A1-A8、映像レイヤー、共有タイムラインprobeを確認。",
  "Faders assigned to the same Cue List share its Back/GO position. Their levels merge HTP; Playback Master scales all Cue-origin intensity without reducing Programmer overrides.":
    "同じキューリストへ割り当てたフェーダーはBack／GO位置を共有します。レベルはHTPでマージされ、プレイバックマスターはプログラマー上書きを下げずにキュー由来の全インテンシティを調整します。",
  "FFmpeg capture runs continuously at 1280x720 / 30fps. Use a camera device name, or leave screen capture blank for the primary desktop.":
    "FFmpeg captureは1280x720／30fpsで連続動作します。カメラデバイス名を指定するか、画面キャプチャを空にしてプライマリデスクトップを使用します。",
  "geometry node(s)": "ジオメトリノード",
  "Grid ms": "グリッド ms",
  "Healthy DMX outputs / configured DMX outputs": "正常DMX出力 / 設定済みDMX出力",
  "Hz target": "目標Hz",
  "I have fenced or disconnected every old Primary.": "旧プライマリをすべて遮断または切断しました。",
  "Install v": "vをインストール",
  "jitter sample(s)": "ジッターサンプル",
  "Layout selected fixtures across the selected object (Shift+1)": "選択灯体を選択オブジェクト全体へ配置（Shift+1）",
  "Layout selected fixtures in a circle (3)": "選択灯体を円形配置（3）",
  "Layout selected fixtures in a grid (2)": "選択灯体をグリッド配置（2）",
  "Layout selected fixtures in a line (1)": "選択灯体を直線配置（1）",
  "Layout selected fixtures in the selected object (Shift+2)": "選択灯体を選択オブジェクト内へ配置（Shift+2）",
  "LTP (input wins)": "LTP（入力優先）",
  "Map selection (": "マップ選択（",
  "mapped channel(s)": "マッピング済みチャンネル",
  "message(s)": "メッセージ",
  "MIB targets (": "MIB対象（",
  "Mirror selected fixtures across X (Shift+[)": "選択灯体をX軸で反転（Shift+[）",
  "Mirror selected fixtures across Z (Shift+])": "選択灯体をZ軸で反転（Shift+]）",
  "Missing geometry reference:": "ジオメトリ参照が見つかりません:",
  "Mode DMX Map": "モードDMXマップ",
  "mode(s) ·": "モード ·",
  "more function(s)": "件の追加機能",
  "Move crop window for": "クロップ範囲を移動:",
  "Multiple Primary sessions are active (": "複数のプライマリセッションが動作中（",
  "NDI input": "NDI入力",
  "No cues. Create one in Control &gt; Live with Store Cue.": "キューがありません。コントロール > ライブでStore Cueしてください。",
  "No cues. Choose a scope, then Store Cue.": "キューがありません。範囲を選び、キューを保存してください。",
  "No cues. Patch fixtures, add video, or create an Effect first.":
    "キューがありません。先に灯体をパッチするか、映像またはエフェクトを作成してください。",
  "No cues. Patch fixtures, add video, create a Node Graph, or create an Effect first.":
    "キューがありません。先に灯体をパッチするか、映像、ノードグラフ、またはエフェクトを作成してください。",
  "No faders on this page. Add a Cue List assignment above.": "このページにフェーダーがありません。上でキューリストを割り当ててください。",
  "No fixtures in this universe. Use Setup &gt; Patch to assign one.": "このユニバースに灯体がありません。セットアップ > パッチで割り当ててください。",
  "No geometry nodes on this fixture.": "この灯体にジオメトリノードはありません。",
  "No geometry nodes.": "ジオメトリノードがありません。",
  "No I/O plan status": "I/Oプラン状態なし",
  "I/O unavailable": "I/Oを利用できません",
  "No lighting targets in this scope.": "この範囲に照明対象がありません。",
  "No matched range": "一致範囲なし",
  "No palettes. Select a fixture, choose a kind, then Capture.": "パレットがありません。灯体と種類を選び、取得してください。",
  "No preview": "プレビューなし",
  "No projection surfaces. Add a Video Output in Setup &gt; Output.": "投影面がありません。セットアップ > 出力で映像出力を追加してください。",
  "No remote clients connected.": "リモートクライアントは接続されていません。",
  "No render plan status": "レンダープラン状態なし",
  "No video layers. Add a file, still, or input above.": "映像レイヤーがありません。上でファイル、静止画、または入力を追加してください。",
  "No video layers. Add one in Setup &gt; Output.": "映像レイヤーがありません。セットアップ > 出力で追加してください。",
  "No video targets in this scope.": "この範囲に映像対象がありません。",
  "Node graph preview": "ノードグラフプレビュー",
  "Non-zero": "非ゼロ",
  Normal: "通常",
  "Normalized projector edge width": "正規化プロジェクターエッジ幅",
  "Note Off": "ノートOFF",
  "Note On": "ノートON",
  Notes: "ノート",
  "Object Grid": "オブジェクトグリッド",
  "Object Line": "オブジェクト直線",
  Off: "OFF",
  Offset: "オフセット",
  "Open All": "全て開く",
  "Open Control category": "コントロールカテゴリを開く",
  "Open Control/Edit with a Position Wave draft for the picked fixtures": "選択灯体の位置ウェーブ下書きをコントロール／編集で開く",
  "Open Stage Map": "ステージマップを開く",
  "Open Window": "ウィンドウを開く",
  Opposite: "反対",
  "Origin X": "原点X",
  "Origin Y": "原点Y",
  "Origin Z": "原点Z",
  "OSC Input": "OSC入力",
  "Output Fade ms": "出力フェード ms",
  "Output label": "出力名",
  "Output Mask": "出力マスク",
  "Output Preview": "出力プレビュー",
  Override: "上書き",
  Page: "ページ",
  "Pan %": "Pan %",
  "Pan stage view": "ステージ表示をパン",
  "Pan stage view (H)": "ステージ表示をパン（H）",
  "Pan tilt axis sliders": "Pan／Tilt軸スライダー",
  "Pan tilt pad": "Pan／Tiltパッド",
  "Pan tilt target points": "Pan／Tilt目標点",
  "Pan value": "Pan値",
  "Parameter data (hex bytes)": "パラメータデータ（16進バイト）",
  Part: "パート",
  "Pattern All": "全パターン",
  "Pattern Preview": "パターンプレビュー",
  Pause: "一時停止",
  "Period ms": "周期 ms",
  Phase: "位相",
  "Phase 1 smoke DMX bytes": "Phase 1スモークDMXバイト",
  "Pick all fixtures currently visible in the mapping filters (Ctrl+A)": "マッピングフィルターで表示中の全灯体を選択（Ctrl+A）",
  "Pick fixtures inside the selected stage object (I)": "選択ステージオブジェクト内の灯体を選択（I）",
  "Pick Inside": "内側を選択",
  "Pick Results": "選択結果",
  "Place selected fixture": "選択灯体を配置",
  "Place selected fixture (P)": "選択灯体を配置（P）",
  Play: "再生",
  "Playback executors": "プレイバックエグゼキューター",
  "Playback Master": "プレイバックマスター",
  "Playback Master level": "プレイバックマスターレベル",
  Playing: "再生中",
  Point: "ポイント",
  points: "ポイント",
  "Polygon + embedded luma bitmap · CPU/GPU parity": "ポリゴン＋埋め込み輝度ビットマップ · CPU/GPU同等",
  "Portable single-pass ISF is embedded in the project. Unsupported resources and unsafe shader constructs are rejected before GPU use.":
    "可搬single-pass ISFはプロジェクトへ埋め込まれます。未対応リソースと危険なシェーダー構造はGPU使用前に拒否します。",
  "Position favorite label": "位置お気に入り名",
  "Position ms": "位置 ms",
  "Position wave clock sync presets": "位置ウェーブクロック同期プリセット",
  "Position wave speed presets": "位置ウェーブ速度プリセット",
  "Position wave wavelength presets": "位置ウェーブ波長プリセット",
  "Pre-wait ms": "事前待機 ms",
  "Preset Label": "プリセット名",
  PREVIEW: "プレビュー",
  "Preview (Reference)": "プレビュー（参照）",
  "Preview Status": "プレビュー状態",
  "preview universe(s)": "プレビューユニバース",
  "Previous layer bank": "前のレイヤーバンク",
  "Previous video output": "前の映像出力",
  "Primary heartbeat is stale. Verify network and Primary power before Take Over.":
    "プライマリのハートビートが停止しています。テイクオーバー前にネットワークとプライマリ電源を確認してください。",
  Probe: "probe",
  "Profile URL": "プロファイルURL",
  "Program audio": "プログラム音声",
  "Projection Surface": "投影面",
  "projection surface(s)": "投影面",
  "projection surface(s) /": "投影面 /",
  "queued poll(s)": "待機poll",
  Radius: "半径",
  "range(s)": "範囲",
  "Raw Attributes": "属性生値",
  "RDM console": "RDMコンソール",
  "RDM Console": "RDMコンソール",
  Readout: "読取値",
  Recapture: "再取得",
  Recent: "最近",
  "reconnect attempt(s)": "再接続試行",
  "Red channel": "赤チャンネル",
  "ref(s)": "参照",
  "reference palette(s)": "参照パレット",
  "Reference palettes": "参照パレット",
  BASS: "低域",
  MID: "中域",
  HIGH: "高域",
  "Clear H": "Hをクリア",
  "Clear P": "Pをクリア",
  "Clear S": "Sをクリア",
  "fixture(s)). Cue references resolve the latest palette value on every GO.": "灯体）。キュー参照はGOのたびに最新のパレット値を解決します。",
  "packet(s) ·": "パケット ·",
  "Reference Palettes (": "参照パレット（",
  "reference(s)": "参照",
  "Refresh audio input devices": "音声入力デバイスを更新",
  "Refresh Metadata": "メタデータを更新",
  rejected: "拒否",
  "Remove Composition": "コンポジションを削除",
  "Remove Fixture": "灯体を削除",
  "Remove List": "リストを削除",
  "Remove Part": "パートを削除",
  "Remove timeline placement": "タイムライン配置を削除",
  "Render Plans": "レンダープラン",
  "Replicate complete show checkpoints through a dedicated shared folder. Standby always follows with DMX and video outputs disarmed.":
    "専用共有フォルダー経由で完全なショーチェックポイントを複製します。スタンバイはDMXと映像出力を無効にしたまま追従します。",
  "Reset Corners": "コーナーをリセット",
  "Reset viewport (0)": "表示領域をリセット（0）",
  "Resize depth of": "奥行きを変更:",
  "Resize width of": "幅を変更:",
  "response block(s) ·": "応答ブロック ·",
  resync: "再同期",
  "RGB channel sliders": "RGBチャンネルスライダー",
  Role: "役割",
  "Rot -15": "-15度回転",
  "Rot +15": "+15度回転",
  "Rotate selected fixtures -15 degrees ([)": "選択灯体を-15度回転（[）",
  "Rotate selected fixtures +15 degrees (])": "選択灯体を+15度回転（]）",
  "Rotate selected fixtures 180 degrees (4)": "選択灯体を180度回転（4）",
  "sACN multicast": "sACNマルチキャスト",
  "Safety mode": "安全モード",
  "Sample Presets": "サンプルプリセット",
  "Sat / Val": "彩度／明度",
  "Sat %": "彩度 %",
  "Save Graph": "グラフを保存",
  "Save project (Ctrl/Cmd+S)": "プロジェクトを保存（Ctrl/Cmd+S）",
  "Save Report": "レポートを保存",
  "Save View": "表示を保存",
  "Saved Preset": "保存済みプリセット",
  Saw: "ノコギリ波",
  Scale: "スケール",
  "Scale X for": "Xスケール:",
  "Scale Y for": "Yスケール:",
  "Scan MIDI": "MIDIをスキャン",
  "Scan Serial": "シリアルをスキャン",
  Screen: "画面",
  "Screen capture": "画面キャプチャ",
  "Search result selection": "検索結果選択",
  "Select a fixture on the map or patch list.": "マップまたはパッチリストで灯体を選択してください。",
  "Select fixture or projection surface": "灯体または投影面を選択",
  "Select fixture or projection surface (S)": "灯体または投影面を選択（S）",
  "Select or patch a fixture.": "灯体を選択またはパッチしてください。",
  "Select port": "ポートを選択",
  "Select UID": "UIDを選択",
  "Select view": "表示を選択",
  "Selected fixture": "選択灯体",
  "Selected Group": "選択グループ",
  "Selected Groups": "選択グループ",
  "Selected mode DMX map": "選択モードDMXマップ",
  "Selected profile geometry": "選択プロファイルジオメトリ",
  "Selection Flags": "選択フラグ",
  "Selection standby": "選択スタンバイ",
  "Send Feedback": "フィードバック送信",
  "Send Routes": "経路へ送信",
  "Send Test": "テスト送信",
  "Set selected fixture yaw": "選択灯体のヨーを設定",
  "Set selected fixture yaw (R)": "選択灯体のヨーを設定（R）",
  "Setup area": "セットアップ領域",
  "Setup workspace": "セットアップワークスペース",
  "Share only the PIN-protected endpoint with trusted operators.": "PINで保護された接続先だけを信頼できるオペレーターへ共有してください。",
  "Shared Folder": "共有フォルダー",
  Show: "ショー",
  Sine: "サイン波",
  Smoke: "スモーク",
  "Snap Items": "項目をスナップ",
  "Snap Off": "スナップOFF",
  "Snap Times": "時刻をスナップ",
  Soft: "ソフト",
  "Solo layer": "レイヤーソロ",
  speed: "速度",
  "Spout input": "Spout入力",
  Square: "矩形波",
  "Stage Bounds": "ステージ範囲",
  "Stage Map": "ステージマップ",
  "Stage edits": "ステージ編集",
  "Stage edits routes faders to the Programmer. Live Preview reaches DMX; Blind changes only the editor preview. Commit writes staged values to the live base state.":
    "ステージ編集ではフェーダーをプログラマーへ送ります。ライブプレビューはDMXへ反映し、ブラインドは編集プレビューだけを変更します。確定すると仮値をライブ基準値へ書き込みます。",
  "Stage Objects": "ステージオブジェクト",
  "Stage Wave": "ステージウェーブ",
  "staged ·": "仮値 ·",
  Standby: "スタンバイ",
  "Start Input": "入力開始",
  "Start OSC": "OSC開始",
  "Start Sync": "同期開始",
  Sat: "彩度",
  "Still image": "静止画",
  "Stop OSC": "OSC停止",
  "Stop Sync": "同期停止",
  "Store Cue": "キューを保存",
  "Save Details": "詳細を保存",
  "Save Recall": "呼び出しを保存",
  "Update Look": "ルックを更新",
  "Saves Cue details only. Effect Recall uses Save Recall.":
    "キューの詳細だけを保存します。エフェクト呼び出しには「呼び出しを保存」を使用してください。",
  "Recaptures the current Store Scope shown above. Recall edits use Save Recall.":
    "上に表示した現在の保存範囲を再取得します。呼び出し設定の編集には「呼び出しを保存」を使用してください。",
  "Patch fixtures, add video, create a Node Graph, or include at least one Effect.":
    "灯体をパッチするか、映像またはノードグラフを追加するか、エフェクトを1つ以上含めてください。",
  "Add video layers, outputs, or Node Graphs before storing a video cue.":
    "映像キューを保存する前に、映像レイヤー、出力、またはノードグラフを追加してください。",
  "Patch fixtures, add video, or include at least one Effect.":
    "灯体をパッチするか、映像を追加するか、エフェクトを1つ以上含めてください。",
  "Patch fixtures or include at least one Effect before storing this Cue.":
    "このキューを保存する前に、灯体をパッチするかエフェクトを1つ以上含めてください。",
  "Include at least one Effect before storing an Effects Only Cue.":
    "エフェクトのみのキューを保存する前に、エフェクトを1つ以上含めてください。",
  Stored: "保存済み",
  "Stored View": "保存済み表示",
  Stretch: "ストレッチ",
  Submaster: "サブマスター",
  "surface(s)": "投影面",
  sync: "同期",
  "Sync Open": "開く状態を同期",
  "Sync Routes": "経路を同期",
  "Sync Window": "ウィンドウを同期",
  "Syphon input": "Syphon入力",
  Take: "テイク",
  "Take fade ms": "テイクフェード ms",
  "Take Over": "テイクオーバー",
  "Take Over loads the latest replicated project with its original DMX and video output state. Confirm the old Primary cannot still transmit.":
    "テイクオーバーは最新の複製プロジェクトを元のDMX・映像出力状態で開きます。旧プライマリが送信できないことを確認してください。",
  "Target groups": "対象グループ",
  "Target H": "対象H",
  "Target IP": "対象IP",
  "Target Selected": "選択対象",
  Test: "テスト",
  "Test Pattern": "テストパターン",
  "This discards all staged values without changing the current live base state.":
    "現在のライブ基準状態を変更せず、全ての仮値を破棄します。",
  Threshold: "しきい値",
  "Tilt %": "Tilt %",
  "Tilt value": "Tilt値",
  "Time ms": "時間 ms",
  "Timeline desk surface": "タイムラインデスク面",
  "Timeline overview": "タイムライン概要",
  "Timeline summary": "タイムライン要約",
  "Timeout ms": "タイムアウト ms",
  "timer deferral(s) ·": "タイマー延期 ·",
  "Toggle beams": "ビーム表示を切替",
  "Toggle beams (B)": "ビーム表示を切替（B）",
  "Toggle fixture level readouts": "灯体レベル表示を切替",
  "Toggle fixture level readouts (Shift+5)": "灯体レベル表示を切替（Shift+5）",
  "Toggle GDTF geometry nodes": "GDTFジオメトリノード表示を切替",
  "Toggle GDTF geometry nodes (G)": "GDTFジオメトリノード表示を切替（G）",
  "Toggle highlight for the picked fixtures (Q)": "選択灯体のハイライトを切替（Q）",
  "Toggle labels": "ラベル表示を切替",
  "Toggle labels (L)": "ラベル表示を切替（L）",
  "Toggle park for the picked fixtures (E)": "選択灯体のパークを切替（E）",
  "Toggle projection surfaces": "投影面表示を切替",
  "Toggle projection surfaces (V)": "投影面表示を切替（V）",
  "Toggle solo for the picked fixtures (W)": "選択灯体のソロを切替（W）",
  "Toggle stage reference objects": "ステージ参照オブジェクト表示を切替",
  "Toggle stage reference objects (O)": "ステージ参照オブジェクト表示を切替（O）",
  Tool: "ツール",
  Top: "上",
  "Touch Cues": "タッチキュー",
  "Touch Fixtures": "タッチ灯体",
  "Touch pan tilt pad": "タッチPan／Tiltパッド",
  "Touch Remote": "タッチリモート",
  "Touch Stage": "タッチステージ",
  "Touch Video": "タッチ映像",
  "Touch workspace": "タッチワークスペース",
  Tracking: "トラッキング",
  "Trusted LAN access": "信頼済みLANアクセス",
  "Trusted LAN access (unencrypted HTTP)": "信頼済みLANアクセス（暗号化なしHTTP）",
  Type: "種類",
  Types: "種類",
  "Universe Overview": "ユニバース概要",
  "Unresolved geometry reference:": "未解決ジオメトリ参照:",
  Update: "更新",
  "us target": "目標 us",
  "Use in Effects": "エフェクトで使用",
  "Use picked fixtures as the Control/Edit effect target": "選択灯体をコントロール／編集のエフェクト対象に使用",
  "Use Profile for Patch": "プロファイルをパッチへ使用",
  "Use Source Length": "ソース長を使用",
  "Use the standard sACN multicast target for the selected universe": "選択ユニバースの標準sACNマルチキャスト宛先を使用",
  "Use Video Output Pos": "映像出力位置を使用",
  "V Blackout": "映像ブラックアウト",
  "V Clear": "映像クリア",
  "Val %": "明度 %",
  Value: "値",
  "value(s)": "値",
  "video /": "映像 /",
  "Video A B deck crossfader": "映像A/Bデッキクロスフェーダー",
  "Video automation rows": "映像オートメーション行",
  "Video clip grid": "映像クリップグリッド",
  "Video layer": "映像レイヤー",
  "Video layer enabled": "映像レイヤー有効",
  "Video Layer label": "映像レイヤー名",
  "Video Layer name": "映像レイヤー名",
  "Video Master": "映像マスター",
  "video output(s) /": "映像出力 /",
  "Video outputs": "映像出力",
  "Video outs": "映像出力",
  warning: "警告",
  "Wave Draft": "ウェーブ下書き",
  "Wave Origin": "ウェーブ原点",
  "Wave shape": "ウェーブ形状",
  "Wave timing": "ウェーブタイミング",
  Wavelength: "波長",
  "Wheel Slots": "ホイールスロット",
  Workspace: "ワークスペース",
  "Workspace context pane": "ワークスペース・コンテキストペイン",
  "X Step": "X間隔",
  "Z Step": "Z間隔",
  Zero: "ゼロ",
  "Zoom -": "縮小 -",
  "Zoom +": "拡大 +",
  "Zoom in (+)": "拡大（+）",
  "Zoom out (-)": "縮小（-）",
  "Select a clip": "クリップを選択",
  "Load A": "Aへ読込",
  "Load B": "Bへ読込",
  Ready: "準備完了",
  Backend: "バックエンド",
  "Backend unavailable": "バックエンド利用不可",
  "Checking backends": "バックエンド確認中",
  "Select ASIO driver": "ASIOドライバを選択",
  "Select rate": "レートを選択",
  "Select fixed buffer": "固定バッファを選択",
  CHECKING: "確認中",
  "NOT BUILT": "未ビルド",
  EMPTY: "入力なし",
  "SELECT DRIVER": "ドライバ選択",
  CONFIGURE: "設定必須",
  FAULT: "障害",
  OPEN: "オープン",
  ACTIVE: "動作中",
  Checking: "確認中",
  "Clear Pending": "クリア待ち",
  "System default audio input": "システム既定の音声入力",
  "Reselect input": "入力を再選択",
  "Reselect audio input": "音声入力を再選択",
  "Bass level": "低域レベル",
  "Mid level": "中域レベル",
  "High level": "高域レベル",
};

const japanesePatterns: Array<[RegExp, (...matches: string[]) => string]> = [
  [/^Built-in FX for (.+) \(layer (\d+)\)$/, (label, id) => `${label}（レイヤー${id}）の内蔵FX`],
  [/^FX stack for (.+) \(layer (\d+)\)$/, (label, id) => `${label}（レイヤー${id}）のFXスタック`],
  [/^(.+) FX enabled for (.+) \(layer (\d+)\)$/, (effect, label, id) => `${label}（レイヤー${id}）の${effect} FX有効状態`],
  [/^FX enabled for (.+) \(layer (\d+)\)$/, (label, id) => `${label}（レイヤー${id}）のFX有効状態`],
  [/^(.+) for (.+) FX on (.+) \(layer (\d+)\)$/, (control, effect, label, id) => `${label}（レイヤー${id}）の${effect} FXの${control}`],
  [/^Advanced FX controls for (.+) \(layer (\d+)\)$/, (label, id) => `${label}（レイヤー${id}）のFX詳細操作`],
  [/^FX error for (.+) \(layer (\d+)\): (.+)$/, (label, id, detail) => `${label}（レイヤー${id}）のFXエラー: ${detail}`],
  [/^(Bypass|Enable) FX (\d+)$/, (action, index) => `FX ${index}を${action === "Bypass" ? "バイパス" : "有効化"}`],
  [/^Move FX (\d+) (up|down)$/, (index, direction) => `FX ${index}を${direction === "up" ? "上" : "下"}へ移動`],
  [/^Reset FX (\d+)$/, (index) => `FX ${index}をリセット`],
  [/^Remove FX (\d+)$/, (index) => `FX ${index}を削除`],
  [/^Trigger (.+) for (.+) \(layer (\d+)\)$/, (control, label, id) => `${label}（レイヤー${id}）の${control}をトリガー`],
  [/^(.+) component (\d+) for (.+) \(layer (\d+)\)$/, (control, component, label, id) => `${label}（レイヤー${id}）の${control} 成分${component}`],
  [/^Clips (Not set|\d+\/\d+)$/, (value) => `クリップ ${value === "Not set" ? "未設定" : value}`],
  [/^(\d+) beats?$/, (beats) => `${beats}ビート`],
  [/^(\d+) pulses?$/, (pulses) => `${pulses}パルス`],
  [
    /^· (CLOCK BEAT|INPUT PULSE) (\d+)$/,
    (trigger, count) => `· ${trigger === "INPUT PULSE" ? "入力パルス" : "クロックビート"} ${count}`,
  ],
  [/^NEXT (\d+|—) · REV (\d+)$/, (next, revision) => `次 ${next} · REV ${revision}`],
  [
    /^INPUT PULSE (\d+) · STEP (\d+)\/(\d+) · FSEQ (\d+|—)$/,
    (pulse, step, interval, feature) => `入力パルス ${pulse} · ステップ ${step}/${interval} · FSEQ ${feature}`,
  ],
  [/^Missing (\d+)$/, (id) => `不明 ${id}`],
  [
    /^Scene Block #(\d+), (.+), (Lighting|Video), starts at (\d+) milliseconds, base duration (\d+) milliseconds, loop count (\d+), effective span (\d+) milliseconds$/,
    (id, label, track, startMs, durationMs, loopCount, spanMs) =>
      `シーンブロック #${id}、${label}、${track === "Lighting" ? "照明" : "映像"}、開始 ${startMs}ミリ秒、基本時間 ${durationMs}ミリ秒、ループ回数 ${loopCount}、実効範囲 ${spanMs}ミリ秒`,
  ],
  [
    /^Point event #(\d+), (.+), (Lighting|Video), at (\d+) milliseconds$/,
    (id, label, track, timeMs) =>
      `ポイントイベント #${id}、${label}、${track === "Lighting" ? "照明" : "映像"}、${timeMs}ミリ秒`,
  ],
  [/^(\d+) shown · (\d+) total$/, (shown, total) => `${shown}件表示 · 全${total}件`],
  [
    /^(Lighting|Video) overlap ×(\d+)$/,
    (track, count) => `${track === "Lighting" ? "照明" : "映像"}の重複 ×${count}`,
  ],
  [
    /^(Lighting|Video) overlap \((\d+)\); (\d+) to (\d+) ms; inspect (\d+) overlapping blocks$/,
    (track, _clusterCount, startMs, endMs, count) =>
      `${track === "Lighting" ? "照明" : "映像"}の重複。${startMs}〜${endMs} ms、${count}ブロックを確認`,
  ],
  [
    /^(Lighting|Video) overlap groups \((\d+)\); (\d+) to (\d+) ms; inspect (\d+) blocks across (\d+) overlap groups$/,
    (track, _clusterCount, startMs, endMs, count, groupCount) =>
      `${track === "Lighting" ? "照明" : "映像"}の重複グループ。${startMs}〜${endMs} ms、${groupCount}グループ内の${count}ブロックを確認`,
  ],
  [
    /^Linked Scene Block · (\d+) ms \/ (\d+) ms × (\d+) \/ (Lighting|Video)$/,
    (timeMs, durationMs, loops, lane) =>
      `連動シーンブロック · ${timeMs} ms / ${durationMs} ms × ${loops}回 / ${lane === "Lighting" ? "照明" : "映像"}`,
  ],
  [
    /^Legacy point · (\d+) ms \/ (Lighting|Video)$/,
    (timeMs, lane) => `旧形式ポイント · ${timeMs} ms / ${lane === "Lighting" ? "照明" : "映像"}`,
  ],
  [/^Nudge (\d+) ms\. Shift-click nudges left\.$/, (timeMs) => `${timeMs} ms微調整。Shiftクリックで左へ移動します。`],
  [/^Blocks (\d+-\d+ \/ \d+)$/, (range) => `ブロック ${range}`],
  [/(^\d+) more · Open Timeline$/, (count) => `他${count}件 · タイムラインを開く`],
  [
    /^L (\d+) · V (\d+) · FX (\d+) · Fade (\d+) ms$/,
    (lighting, video, effects, fadeMs) =>
      `照明 ${lighting} · 映像 ${video} · FX ${effects} · フェード ${fadeMs} ms`,
  ],
  [/^(\d+) ms × (\d+) = (\d+) ms span$/, (durationMs, loops, spanMs) => `${durationMs} ms × ${loops}回 = ${spanMs} ms`],
  [
    /^(.+) \/ (Lighting|Video) \/ (\d+) ms \/ (\d+) ms x (\d+)$/,
    (label, track, timeMs, durationMs, loops) =>
      `${label} / ${track === "Lighting" ? "照明" : "映像"} / ${timeMs} ms / ${durationMs} ms × ${loops}回`,
  ],
  [
    /^(.+) \/ (Lighting|Video) \/ (\d+) ms \/ legacy point$/,
    (label, track, timeMs) =>
      `${label} / ${track === "Lighting" ? "照明" : "映像"} / ${timeMs} ms / 旧形式ポイント`,
  ],
  [/^Place at the current playhead \((\d+) ms\)$/, (timeMs) => `現在の再生位置（${timeMs} ms）へ配置`],
  [
    /^Added linked Scene Block (\d+) at (\d+) ms \((\d+) ms × (\d+)\)$/,
    (id, timeMs, durationMs, loops) =>
      `連動シーンブロック ${id} を ${timeMs} ms に追加しました（${durationMs} ms × ${loops}回）`,
  ],
  [/^Saved linked Scene Block (\d+)$/, (id) => `連動シーンブロック ${id} を保存しました`],
  [/^Saved legacy timeline point (\d+)$/, (id) => `旧形式のタイムラインポイント ${id} を保存しました`],
  [
    /^Moved (Scene Block|timeline point) (\d+) to (\d+) ms$/,
    (kind, id, timeMs) =>
      `${kind === "Scene Block" ? "シーンブロック" : "タイムラインポイント"} ${id} を ${timeMs} ms へ移動しました`,
  ],
  [/^Timeline event (\d+) was not found\.$/, (id) => `タイムラインイベント ${id} が見つかりません。`],
  [/^Moved Cue (\d+) to (\d+) ms$/, (id, timeMs) => `キュー ${id} を ${timeMs} ms へ移動しました`],
  [
    /^Removed (Scene Block|timeline point) (\d+)$/,
    (kind, id) => `${kind === "Scene Block" ? "シーンブロック" : "タイムラインポイント"} ${id} を削除しました`,
  ],
  [
    /^(Block|Point) (\d+) · (.+) @ (\d+)ms$/,
    (kind, id, label, timeMs) =>
      `${kind === "Block" ? "ブロック" : "ポイント"} ${id} · ${label} @ ${timeMs}ms`,
  ],
  [
    /^Repeat this block · (Block|Point) (\d+) · (.+) @ (\d+)ms$/,
    (kind, id, label, timeMs) =>
      `この${kind === "Block" ? "ブロック" : "ポイント"}を繰り返す · ${kind === "Block" ? "ブロック" : "ポイント"} ${id} · ${label} @ ${timeMs}ms`,
  ],
  [
    /^Jump · (Block|Point) (\d+) · (.+) @ (\d+)ms$/,
    (kind, id, label, timeMs) =>
      `ジャンプ · ${kind === "Block" ? "ブロック" : "ポイント"} ${id} · ${label} @ ${timeMs}ms`,
  ],
  [/^Include Effect (\d+) (.+)$/, (id, label) => `エフェクト ${id} ${label} を対象に含める`],
  [/^Recall Effect (\d+) (ON|OFF)$/, (id, state) => `エフェクト ${id} を${state}で呼び出す`],
  [/^Updated cue (\d+) look from the current Store Scope\.$/, (id) => `キュー ${id} のルックを現在の保存範囲から更新しました。`],
  [/^Saved cue (\d+) Effect Recall only\.$/, (id) => `キュー ${id} のエフェクト呼び出しだけを保存しました。`],
  [/^Saved cue (\d+) details only\. Effect Recall is unchanged\.$/, (id) => `キュー ${id} の詳細だけを保存しました。エフェクト呼び出しは変更していません。`],
  [/^Color effect gradient with (\d+) stops$/, (count) => `${count}色のカラーエフェクトグラデーション`],
  [/^Color for palette stop (\d+)$/, (index) => `パレットストップ${index}の色`],
  [/^Hex color for palette stop (\d+)$/, (index) => `パレットストップ${index}のHEXカラー`],
  [/^Position for palette stop (\d+)$/, (index) => `パレットストップ${index}の位置`],
  [/^Move palette stop (\d+) up$/, (index) => `パレットストップ${index}を上へ移動`],
  [/^Move palette stop (\d+) down$/, (index) => `パレットストップ${index}を下へ移動`],
  [/^Remove palette stop (\d+)$/, (index) => `パレットストップ${index}を削除`],
  [/^(\d+) color stops$/, (count) => `${count}色`],
  [/^(\d+) \/ 8 stops$/, (count) => `${count} / 8ストップ`],
  [/^spread (\d+)%$/, (percent) => `スプレッド ${percent}%`],
  [/^LOOP ON · (.+)–(.+)$/, (start, end) => `ループ ON · ${start}–${end}`],
  [/^Stage (.+) in Preview without changing Program$/, (label) => `Programを変えずに${label}をPreviewへ送る`],
  [/^(\d+) steps?$/, (count) => `${count} 手順`],
  [/^Install v(.+)$/, (version) => `v${version}をインストール`],
  [/^(\d+)% downloaded$/, (percent) => `${percent}% ダウンロード済み`],
  [/^(\d+) percent$/, (percent) => `${percent}パーセント`],
  [/^(Bass|Mid|High) (\d+)%$/, (band, percent) => `${band === "Bass" ? "低域" : band === "Mid" ? "中域" : "高域"} ${percent}%`],
  [/^Found (\d+) audio input device\(s\)\.$/, (count) => `音声入力デバイスが${count}件見つかりました。`],
  [/^(\d+) MB downloaded$/, (megabytes) => `${megabytes} MB ダウンロード済み`],
  [/^Saved project (.+)$/, (path) => `プロジェクトを保存しました: ${path}`],
  [/^Loaded project (.+)$/, (detail) => `プロジェクトを読み込みました: ${detail}`],
  [/^Saved user template (.+)$/, (path) => `ユーザーテンプレートを保存しました: ${path}`],
  [/^Template save failed: (.+)$/, (detail) => `テンプレート保存に失敗しました: ${detail}`],
  [/^Template load failed: (.+)$/, (detail) => `テンプレート読込に失敗しました: ${detail}`],
  [
    /^Created an unsaved project from (.+) \((\d+) embedded profiles?, (\d+) MIDI, (\d+) OSC mappings\)\. All DMX and video outputs are disabled and blacked out\.$/,
    (label, profiles, midi, osc) =>
      `${label}から未保存プロジェクトを作成しました（埋め込みプロファイル ${profiles}、MIDI ${midi}、OSC ${osc}）。DMXと映像出力はすべて無効・ブラックアウトです。`,
  ],
  [/^Project backup restore failed: (.+)$/, (detail) => `バックアップ復元に失敗しました: ${detail}`],
  [/^Downloading signed Syndocal (.+) update\.\.\.$/, (version) => `署名付きSyndocal ${version}をダウンロード中...`],
  [/^Syndocal (.+) was verified and handed to the platform installer\.$/, (version) => `Syndocal ${version}を検証し、OSインストーラーへ渡しました。`],
  [/^Update install failed: (.+)$/, (detail) => `更新のインストールに失敗しました: ${detail}`],
  [/^Update check failed: (.+)$/, (detail) => `更新確認に失敗しました: ${detail}`],
  [/^Analyzed audio (.+)$/, (detail) => `音声を解析しました: ${detail}`],
  [/^Applied audio BPM (.+)$/, (bpm) => `音声BPM ${bpm}を適用しました`],
  [
    /^VJ show ready with (\d+) clips?\(s\)\. VJ Program remains Off and Blackout until you enable it explicitly\.$/,
    (clips) => `VJショーを${clips}クリップで準備しました。明示的に有効化するまでVJ ProgramはOff・Blackoutのままです。`,
  ],
];

export function uiLocaleFromUnknown(value: unknown): UiLocale {
  return value === "ja" ? "ja" : "en";
}

export function loadUiLocale(): UiLocale {
  try {
    return uiLocaleFromUnknown(window.localStorage.getItem(uiLocaleStorageKey));
  } catch {
    return "en";
  }
}

export function saveUiLocale(locale: UiLocale): boolean {
  try {
    window.localStorage.setItem(uiLocaleStorageKey, locale);
    return true;
  } catch {
    return false;
  }
}

export function translateUiText(value: string, locale: UiLocale): string {
  if (locale === "en") return value;
  const leading = value.match(/^\s*/)?.[0] ?? "";
  const trailing = value.match(/\s*$/)?.[0] ?? "";
  const text = value.trim();
  if (!text) return value;
  const exact = japaneseText[text];
  if (exact) return `${leading}${exact}${trailing}`;
  for (const [pattern, render] of japanesePatterns) {
    const match = text.match(pattern);
    if (match) return `${leading}${render(...match.slice(1))}${trailing}`;
  }
  return value;
}

export interface TimelineOverviewMarkerAccessibleEvent {
  id: number;
  cue_label: string;
  track: "Lighting" | "Video";
  time_ms: number;
  duration_ms: number;
  loop_count: number;
  total_duration_ms: number;
}

export function timelineOverviewMarkerAriaLabel(
  event: TimelineOverviewMarkerAccessibleEvent,
  locale: UiLocale,
): string {
  const source = event.duration_ms > 0
    ? `Scene Block #${event.id}, ${event.cue_label}, ${event.track}, starts at ${event.time_ms} milliseconds, base duration ${event.duration_ms} milliseconds, loop count ${event.loop_count}, effective span ${event.total_duration_ms} milliseconds`
    : `Point event #${event.id}, ${event.cue_label}, ${event.track}, at ${event.time_ms} milliseconds`;
  return translateUiText(source, locale);
}

type RenderState = { source: string; rendered: string };
const textStates = new WeakMap<Text, RenderState>();
const attributeStates = new WeakMap<Element, Map<string, RenderState>>();
const translatedAttributes = ["title", "aria-label", "aria-valuetext", "placeholder"] as const;

function localizeTextNode(node: Text, locale: UiLocale) {
  const parent = node.parentElement;
  if (!parent || parent.closest("script, style, textarea, [data-no-localize]")) return;
  const current = node.nodeValue ?? "";
  let state = textStates.get(node);
  if (!state || current !== state.rendered) {
    state = { source: current, rendered: current };
  }
  const rendered = translateUiText(state.source, locale);
  state.rendered = rendered;
  textStates.set(node, state);
  if (current !== rendered) node.nodeValue = rendered;
}

function localizeElementAttributes(element: Element, locale: UiLocale) {
  let states = attributeStates.get(element);
  if (!states) {
    states = new Map();
    attributeStates.set(element, states);
  }
  for (const attribute of translatedAttributes) {
    if (!element.hasAttribute(attribute)) continue;
    const current = element.getAttribute(attribute) ?? "";
    let state = states.get(attribute);
    if (!state || current !== state.rendered) {
      state = { source: current, rendered: current };
    }
    const rendered = translateUiText(state.source, locale);
    state.rendered = rendered;
    states.set(attribute, state);
    if (current !== rendered) element.setAttribute(attribute, rendered);
  }
}

function localizeNode(node: Node, locale: UiLocale) {
  if (node instanceof Text) {
    localizeTextNode(node, locale);
    return;
  }
  if (!(node instanceof Element)) return;
  localizeElementAttributes(node, locale);
  const walker = document.createTreeWalker(node, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
  let descendant = walker.nextNode();
  while (descendant) {
    if (descendant instanceof Text) localizeTextNode(descendant, locale);
    else if (descendant instanceof Element) localizeElementAttributes(descendant, locale);
    descendant = walker.nextNode();
  }
}

export function installUiLocalization(root: HTMLElement, getLocale: () => UiLocale) {
  let queued = false;
  const pending = new Set<Node>();
  const refresh = () => {
    document.documentElement.lang = getLocale() === "ja" ? "ja" : "en";
    localizeNode(root, getLocale());
  };
  const queuePending = () => {
    if (queued) return;
    queued = true;
    queueMicrotask(() => {
      queued = false;
      const locale = getLocale();
      document.documentElement.lang = locale === "ja" ? "ja" : "en";
      for (const node of pending) localizeNode(node, locale);
      pending.clear();
    });
  };
  const observer = new MutationObserver((mutations) => {
    for (const mutation of mutations) {
      if (mutation.type === "childList") {
        for (const node of mutation.addedNodes) pending.add(node);
      } else {
        pending.add(mutation.target);
      }
    }
    if (pending.size > 0) queuePending();
  });
  observer.observe(root, {
    subtree: true,
    childList: true,
    characterData: true,
    attributes: true,
    attributeFilter: [...translatedAttributes],
  });
  refresh();
  return {
    refresh,
    dispose: () => observer.disconnect(),
  };
}
