[package]
name = "io"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
ndi = ["dep:grafton-ndi"]

[dependencies]
crossbeam-queue.workspace = true
grafton-ndi = { workspace = true, optional = true }
midir.workspace = true
protocol.workspace = true
rosc.workspace = true
serde_json.workspace = true
serialport.workspace = true
thiserror.workspace = true
tungstenite.workspace = true
